### ISSUE TITLE
easy way to find virtualenv path

### ISSUE THREAD

**Issue by rlittlefield** [sdispater/poetry#106]
It would be helpful if there was a simple command to determine the path to the current virtualenv. I can easily enough run `poetry run which python`, but that may not be the first idea. This is helpful for both running commands without prefixing them with `poetry run` every time, and also helpful for IDEs like PyCharm that want to know where the virtualenv lives.

Something like `poetry virtualenv`.

**Comment by cauebs** [comment]
@sdispater After the `shell` stuff, this is definitely something I can handle, hahah. What's your take on this?

**Comment by sdispater** [comment]
This will be supported in the next major version (`1.0.0`). See https://github.com/sdispater/poetry/pull/731 for more information.

**Comment by stephsamson** [comment]
This issue will be closed since:
* `poetry show -v` also already gives you this information
* PR #731 resolves this with a nicer interface than `poetry show -v`

**Comment by sebdiem** [comment]
Thanks for the command. However I was surprised to note that

```
poetry show -v | head -n 1
```

is not handled very well 

```
Traceback (most recent call last):
  File "/Users/seb/.poetry/lib/poetry/_vendor/py3.7/clikit/console_application.py", line 131, in run
    status_code = command.handle(parsed_args, io)
  File "/Users/seb/.poetry/lib/poetry/_vendor/py3.7/clikit/api/command/command.py", line 120, in handle
    status_code = self._do_handle(args, io)
  File "/Users/seb/.poetry/lib/poetry/_vendor/py3.7/clikit/api/command/command.py", line 171, in _do_handle
    return getattr(handler, handler_method)(args, io, self)
  File "/Users/seb/.poetry/lib/poetry/_vendor/py3.7/cleo/commands/command.py", line 92, in wrap_handle
    return self.handle()
  File "/Users/seb/.poetry/lib/poetry/console/commands/show.py", line 256, in handle
    self.line(line)
  File "/Users/seb/.poetry/lib/poetry/_vendor/py3.7/cleo/commands/command.py", line 233, in line
    self._io.write_line(styled, verbosity)
  File "/Users/seb/.poetry/lib/poetry/_vendor/py3.7/cleo/io/io_mixin.py", line 65, in write_line
    super(IOMixin, self).write_line(string, flags)
  File "/Users/seb/.poetry/lib/poetry/_vendor/py3.7/clikit/api/io/io.py", line 66, in write_line
    self._output.write_line(string, flags=flags)
  File "/Users/seb/.poetry/lib/poetry/_vendor/py3.7/clikit/api/io/output.py", line 69, in write_line
    self.write(string, flags=flags, new_line=True)
  File "/Users/seb/.poetry/lib/poetry/_vendor/py3.7/clikit/api/io/output.py", line 61, in write
    self._stream.write(to_str(formatted))
  File "/Users/seb/.poetry/lib/poetry/_vendor/py3.7/clikit/io/output_stream/stream_output_stream.py", line 25, in write
    self._stream.flush()
BrokenPipeError: [Errno 32] Broken pipe
```

I can understand why, but it may be annoying not to be able to compose this command the "unix" way.

**Comment by lucidyan** [comment]
@sebdiem Yes, it's frustrating a bit. After some time I found the command that extract virtualenv path for me:
```bash
poetry show -v 2> /dev/null | head -n1 | cut -d ' ' -f 3
```

**Comment by finswimmer** [comment]
@sebdiem: I guess `poetry env info -p` is what you are looking for.

**Comment by IMRAAN012** [comment]
I got:   echo $VIRTUAL_ENV

**Comment by neersighted** [comment]
`poetry env info --path`
