### ISSUE TITLE
Fish: `poetry shell` exits on Ctrl-C

### ISSUE THREAD

**Issue by dimaqq** [sdispater/poetry#1112]
```
… ~/aproject> poetry shell
Spawning shell within /Users/user.name/Library/Caches/pypoetry/virtualenvs/aproject-wNEHA9fb-py3.7
Welcome to fish, the friendly interactive shell

# when shell prompt shows up, hit Ctril-C

… ~/aproject> Traceback (most recent call last):
  File "/Users/user.name/.poetry/bin/poetry", line 13, in <module>
    main()
  File "/Users/user.name/.poetry/lib/poetry/console/__init__.py", line 5, in main
    return Application().run()
  File "/Users/user.name/.poetry/lib/poetry/_vendor/py3.7/clikit/console_application.py", line 131, in run
    status_code = command.handle(parsed_args, io)
  File "/Users/user.name/.poetry/lib/poetry/_vendor/py3.7/clikit/api/command/command.py", line 112, in handle
    status_code = self._do_handle(args, io)
  File "/Users/user.name/.poetry/lib/poetry/_vendor/py3.7/clikit/api/command/command.py", line 160, in _do_handle
    return getattr(handler, handler_method)(args, io, self)
  File "/Users/user.name/.poetry/lib/poetry/_vendor/py3.7/cleo/commands/command.py", line 92, in wrap_handle
    return self.handle()
  File "/Users/user.name/.poetry/lib/poetry/console/commands/shell.py", line 41, in handle
    self.env.execute(shell.path)
  File "/Users/user.name/.poetry/lib/poetry/utils/env.py", line 828, in execute
    return super(VirtualEnv, self).execute(bin, *args, **kwargs)
  File "/Users/user.name/.poetry/lib/poetry/utils/env.py", line 684, in execute
    return subprocess.call([bin] + list(args), **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 325, in call
    return p.wait(timeout=timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 990, in wait
    return self._wait(timeout=timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 1624, in _wait
    (pid, sts) = self._try_wait(0)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 1582, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
KeyboardInterrupt
```

- [ ] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version. (TBD, currently `Poetry version 1.0.0a2`)
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option). (I don't know what the command was)

- **OS version and name**: MacOS latest
- **Poetry version**: 1.0.0.a2
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: it's private
- `fish, version 3.0.2`

**Comment by dimaqq** [comment]
There's something else I've found out — `poetry shell` appears to exit with the same symptom.
I can't be sure where the bug is, whether `poetry` or `fish` shell 😕 
So far I could not reproduce this oddity in `bash` where I don't have extensive autocomplete, I'll try some more!

**Comment by kosayoda** [comment]
While searching for this issue I found #823, which also has the same problem and has a slightly icky temporary workaround~

**Comment by dimaqq** [comment]
No longer a problem in `Poetry version 1.0.0b4`, closing!
