### ISSUE TITLE
FileExistsError after adding a locally referenced package

### ISSUE THREAD

**Issue by osvaldolove** [sdispater/poetry#1218]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate. - it is similar to issue #1123
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Windows 10 Enterprise Version 1809 (OS Build 17763.615)
- **Poetry version**: Poetry 0.12.17

## Issue
Whenever I try to add another package after adding one that references a local package I receive the following error
`FileExistsError: [WinError 183] Cannot create a file when that file already exists`

Steps to replicate.
```shell
poetry new project-a
poetry new project-b
cd project-b
poetry add project-a --path ../project-a/
poetry add pylint --dev -vvv
```

And here is my full shell output from doing the above.
```
PS C:\Users\Olly\Source\Repos\python> poetry new project-a
Created package project-a in project-a
PS C:\Users\Olly\Source\Repos\python> poetry new project-b
Created package project-b in project-b
PS C:\Users\Olly\Source\Repos\python> cd .\project-b\
PS C:\Users\Olly\Source\Repos\python\project-b> poetry add project-a --path ../project-a/
Creating virtualenv project-b-py3.7 in C:\Users\Olly\Source\Repos\python\project-b\.venv

Updating dependencies
Resolving dependencies...

Writing lock file


Package operations: 11 installs, 0 updates, 0 removals

  - Installing zipp (0.5.2)
  - Installing importlib-metadata (0.18)
  - Installing atomicwrites (1.3.0)
  - Installing attrs (19.1.0)
  - Installing colorama (0.4.1)
  - Installing more-itertools (7.1.0)
  - Installing pluggy (0.12.0)
  - Installing py (1.8.0)
  - Installing six (1.12.0)
  - Installing project-a (0.1.0 ../project-a)
  - Installing pytest (3.10.1)
PS C:\Users\Olly\Source\Repos\python\project-b> poetry add pylint --dev -vvv
Using virtualenv: C:\Users\Olly\Source\Repos\python\project-b\.venv 
PyPI: No release information found for pylint-0.10.0, skipping 
PyPI: No release information found for pylint-0.11.0, skipping 
PyPI: No release information found for pylint-0.12.1, skipping
PyPI: No release information found for pylint-0.13.0, skipping
PyPI: No release information found for pylint-0.14.0, skipping
PyPI: No release information found for pylint-0.4.1, skipping
PyPI: No release information found for pylint-0.6.0, skipping
PyPI: No release information found for pylint-0.6.1, skipping 
PyPI: No release information found for pylint-0.7.0, skipping
PyPI: No release information found for pylint-0.8.1, skipping
PyPI: 71 packages found for pylint *
Using version ^2.3 for pylint

Updating dependencies 
Resolving dependencies... 
   1: fact: project-b is 0.1.0
   1: derived: project-b
   1: fact: project-b depends on project-a (*) 
   1: fact: project-b depends on pytest (^3.0)
   1: fact: project-b depends on pylint (^2.3)
   1: selecting project-b (0.1.0)
   1: derived: pylint (^2.3)
   1: derived: pytest (^3.0)
   1: derived: project-a (*)
PyPI: No release information found for pylint-0.10.0, skipping 
PyPI: No release information found for pylint-0.11.0, skipping
PyPI: No release information found for pylint-0.12.1, skipping
PyPI: No release information found for pylint-0.13.0, skipping
PyPI: No release information found for pylint-0.14.0, skipping
PyPI: No release information found for pylint-0.4.1, skipping 
PyPI: No release information found for pylint-0.6.0, skipping
PyPI: No release information found for pylint-0.6.1, skipping
PyPI: No release information found for pylint-0.7.0, skipping
PyPI: No release information found for pylint-0.8.1, skipping
PyPI: 2 packages found for pylint >=2.3,<3.0
   1: fact: pylint (2.3.1) depends on astroid (>=2.2.0,<3) 
   1: fact: pylint (2.3.1) depends on isort (>=4.2.5,<5)
   1: fact: pylint (2.3.1) depends on mccabe (>=0.6,<0.7)
   1: fact: pylint (2.3.1) depends on colorama (*)
   1: selecting pylint (2.3.1)
   1: derived: colorama (*) 
   1: derived: mccabe (>=0.6,<0.7)
   1: derived: isort (>=4.2.5,<5)
   1: derived: astroid (>=2.2.0,<3)
PyPI: No release information found for mccabe-0.0.0, skipping 
PyPI: 2 packages found for mccabe >=0.6,<0.7 
PyPI: 30 packages found for isort >=4.2.5,<5 
PyPI: 6 packages found for astroid >=2.2.0,<3 
   1: fact: pytest (3.10.1) depends on py (>=1.5.0) 
   1: fact: pytest (3.10.1) depends on six (>=1.10.0)
   1: fact: pytest (3.10.1) depends on attrs (>=17.4.0)
   1: fact: pytest (3.10.1) depends on more-itertools (>=4.0.0)
   1: fact: pytest (3.10.1) depends on atomicwrites (>=1.0)
   1: fact: pytest (3.10.1) depends on pluggy (>=0.7)
   1: fact: pytest (3.10.1) depends on colorama (*)
   1: selecting pytest (3.10.1) 
   1: derived: pluggy (>=0.7)
   1: derived: atomicwrites (>=1.0)
   1: derived: more-itertools (>=4.0.0)
   1: derived: attrs (>=17.4.0)
   1: derived: six (>=1.10.0)
   1: derived: py (>=1.5.0)
   1: selecting project-a (0.1.0 ../project-a)
   1: selecting colorama (0.4.1) 
   1: fact: pluggy (0.12.0) depends on importlib-metadata (>=0.12)
   1: selecting pluggy (0.12.0) 
   1: derived: importlib-metadata (>=0.12)
   1: selecting atomicwrites (1.3.0)
   1: selecting more-itertools (7.1.0)
   1: selecting attrs (19.1.0) 
   1: selecting six (1.12.0) 
   1: selecting py (1.8.0)
PyPI: Invalid constraint (pathlib2 ; python_version == "3.4.*" or python_version < "3") found in importlib-metadata-0.18 dependencies, skipping 
   1: fact: importlib-metadata (0.18) depends on zipp (>=0.5) 
   1: selecting importlib-metadata (0.18)
   1: derived: zipp (>=0.5)
   1: selecting zipp (0.5.2) 
   1: selecting mccabe (0.6.1)
   1: fact: astroid (2.2.5) depends on lazy-object-proxy (*) 
   1: fact: astroid (2.2.5) depends on six (*)
   1: fact: astroid (2.2.5) depends on wrapt (*)
   1: fact: astroid (2.2.5) depends on typed-ast (>=1.3.0)
   1: selecting astroid (2.2.5)
   1: derived: typed-ast (>=1.3.0)
   1: derived: wrapt (*) 
   1: derived: lazy-object-proxy (*)
PyPI: 6 packages found for typed-ast >=1.3.0 
PyPI: No release information found for wrapt-0.0.0, skipping 
PyPI: No release information found for wrapt-1.10.3, skipping 
PyPI: 33 packages found for wrapt *
PyPI: No release information found for lazy-object-proxy-0.0.1, skipping 
PyPI: 12 packages found for lazy-object-proxy * 
   1: selecting typed-ast (1.4.0)
   1: selecting lazy-object-proxy (1.4.1)
   1: selecting isort (4.3.21) 
   1: selecting wrapt (1.11.2) 
   1: Version solving took 0.418 seconds.
   1: Tried 1 solutions.

Writing lock file 


Package operations: 8 installs, 0 updates, 0 removals

  - Installing lazy-object-proxy (1.4.1)
  - Installing typed-ast (1.4.0) 
  - Installing wrapt (1.11.2) 
  - Installing astroid (2.2.5) 
  - Installing isort (4.3.21) 
  - Installing mccabe (0.6.1) 
  - Installing project-a (0.1.0 ../project-a) 


[EnvCommandError]
Command ['C:\\Users\\Olly\\Source\\Repos\\python\\project-b\\.venv\\Scripts\\python.exe', '-m', 'pip', 'install', '--no-deps', '-U', '-e', 'C:\\Users\\Olly\\Source\\Repos\\python\\project-a'] errored with the following return code 1, and output:

Obtaining file:///C:/Users/Olly/Source/Repos/python/project-a
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
    Preparing wheel metadata: started
    Preparing wheel metadata: finished with status 'error'
    Complete output from command C:\Users\Olly\Source\Repos\python\project-b\.venv\Scripts\python.exe C:\Users\Olly\Source\Repos\python\project-b\.venv\lib\site-packages\pip\_vendor\pep517\_in_process.py prepare_metadata_for_build_wheel C:\Users\Olly\AppData\Local\Temp\tmp7lgz    
z6s8:
    Traceback (most recent call last):
      File "C:\Users\Olly\Source\Repos\python\project-b\.venv\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 207, in <module>
        main()
      File "C:\Users\Olly\Source\Repos\python\project-b\.venv\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 197, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "C:\Users\Olly\Source\Repos\python\project-b\.venv\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 69, in prepare_metadata_for_build_wheel
        return hook(metadata_directory, config_settings)
      File "C:\Users\Olly\AppData\Local\Temp\pip-build-env-8h5ztove\overlay\Lib\site-packages\poetry\masonry\api.py", line 39, in prepare_metadata_for_build_wheel
        dist_info.mkdir()
      File "c:\python37\lib\pathlib.py", line 1258, in mkdir
        self._accessor.mkdir(self, mode)
    FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'C:\\Users\\Olly\\Source\\Repos\\python\\project-a\\pip-wheel-metadata\\project_a-0.1.0.dist-info'


    ----------------------------------------
Command "C:\Users\Olly\Source\Repos\python\project-b\.venv\Scripts\python.exe C:\Users\Olly\Source\Repos\python\project-b\.venv\lib\site-packages\pip\_vendor\pep517\_in_process.py prepare_metadata_for_build_wheel C:\Users\Olly\AppData\Local\Temp\tmp7lgzz6s8" failed with error     
code 1 in C:\Users\Olly\Source\Repos\python\project-a
You are using pip version 19.0.3, however version 19.1.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.


Exception trace:
 c:\users\olly\.local\pipx\venvs\poetry\lib\site-packages\cleo\application.py in run() at line 94
   status_code = self.do_run(input_, output_)
 c:\users\olly\.local\pipx\venvs\poetry\lib\site-packages\poetry\console\application.py in do_run() at line 88
   return super(Application, self).do_run(i, o)
 c:\users\olly\.local\pipx\venvs\poetry\lib\site-packages\cleo\application.py in do_run() at line 197
   status_code = command.run(input_, output_)
 c:\users\olly\.local\pipx\venvs\poetry\lib\site-packages\poetry\console\commands\command.py in run() at line 77
   return super(BaseCommand, self).run(i, o)
 c:\users\olly\.local\pipx\venvs\poetry\lib\site-packages\cleo\commands\base_command.py in run() at line 146
   status_code = self.execute(input_, output_)
 c:\users\olly\.local\pipx\venvs\poetry\lib\site-packages\cleo\commands\command.py in execute() at line 107
   return self.handle()
 c:\users\olly\.local\pipx\venvs\poetry\lib\site-packages\poetry\console\commands\add.py in handle() at line 139
   status = installer.run()
 c:\users\olly\.local\pipx\venvs\poetry\lib\site-packages\poetry\installation\installer.py in run() at line 73
   self._do_install(local_repo)
 c:\users\olly\.local\pipx\venvs\poetry\lib\site-packages\poetry\installation\installer.py in _do_install() at line 290
   self._execute(op)
 c:\users\olly\.local\pipx\venvs\poetry\lib\site-packages\poetry\installation\installer.py in _execute() at line 306
   getattr(self, "_execute_{}".format(method))(operation)
 c:\users\olly\.local\pipx\venvs\poetry\lib\site-packages\poetry\installation\installer.py in _execute_install() at line 331
   self._installer.install(operation.package)
 c:\users\olly\.local\pipx\venvs\poetry\lib\site-packages\poetry\installation\pip_installer.py in install() at line 30
   self.install_directory(package)
 c:\users\olly\.local\pipx\venvs\poetry\lib\site-packages\poetry\installation\pip_installer.py in install_directory() at line 205
   return self.run(*args)
 c:\users\olly\.local\pipx\venvs\poetry\lib\site-packages\poetry\installation\pip_installer.py in run() at line 112
   return self._env.run("python", "-m", "pip", *args, **kwargs)
 c:\users\olly\.local\pipx\venvs\poetry\lib\site-packages\poetry\utils\env.py in run() at line 539
   return super(VirtualEnv, self).run(bin, *args, **kwargs)
 c:\users\olly\.local\pipx\venvs\poetry\lib\site-packages\poetry\utils\env.py in run() at line 388
   raise EnvCommandError(e, input=input_)

add [-D|--dev] [--git GIT] [--path PATH] [-E|--extras EXTRAS] [--optional] [--python PYTHON] [--platform PLATFORM] [--allow-prereleases] [--dry-run] [--] <name> (<name>)...
```

Thanks

**Comment by osvaldolove** [comment]
Note, a workaround is to delete the ../project-a/pip-wheel-metadata folder prior to running poetry commands in project-b.

**Comment by osvaldolove** [comment]
Turns out this identical to issue #1123 so closing this one.
