### ISSUE TITLE
typing-extensions has incorrect dependency of typing detected

### ISSUE THREAD

**Issue by tbsf** [sdispater/poetry#1258]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macOS 10.14.5
- **Poetry version**: Poetry 0.12.17
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/tbsf/8cd6345e6e2bb55739b275cb4da2763d

## Issue

Poetry is incorrectly resolving that typing-extensions has a dependency of typing on python 3.7.

```
» /usr/local/bin/python3.7 -Wignore -m poetry debug:resolve --tree                                                                                                                                                   ~/Workspace/bep_schemas/test_proj  
Resolving dependencies... (0.1s)

Resolution results:

typing-extensions 3.7.4 Backported and Experimental Type Hints for Python 3.5+
└── typing >=3.7.4
```

The [setup.py for typing-extensions](https://github.com/python/typing/blob/master/typing_extensions/setup.py) contains the following:

```
install_requires = []
if sys.version_info < (3, 5):
    install_requires.append('typing >= 3.7.4')
```

It should detect the if statement and not include typing.

**Comment by gcarq** [comment]
Same issue here.
This is a problem since `typing` is not compatible with python3.7 and raises the following exception:
```
  Traceback (most recent call last):                                          
    File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_ma  
in                                                                            
      "__main__", mod_spec)                                                   
    File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code           
      exec(code, run_globals)                                                 
    File "/usr/local/lib/python3.7/site-packages/pip/__main__.py", line 16,   
in <module>                                                                   
      from pip._internal import main as _main  # isort:skip # noqa            
    File "/usr/local/lib/python3.7/site-packages/pip/_internal/__init__.py",  
 line 40, in <module>                                                         
      from pip._internal.cli.autocompletion import autocomplete               
    File "/usr/local/lib/python3.7/site-packages/pip/_internal/cli/autocompl  
etion.py", line 8, in <module>                                                
      from pip._internal.cli.main_parser import create_main_parser            
    File "/usr/local/lib/python3.7/site-packages/pip/_internal/cli/main_pars  
er.py", line 7, in <module>                                                   
      from pip._internal.cli import cmdoptions                                
    File "/usr/local/lib/python3.7/site-packages/pip/_internal/cli/cmdoption  
s.py", line 24, in <module>                                                   
      from pip._internal.models.search_scope import SearchScope               
    File "/usr/local/lib/python3.7/site-packages/pip/_internal/models/search  
_scope.py", line 11, in <module>                                              
      from pip._internal.utils.misc import normalize_path, redact_password_f  
rom_url                                                                       
    File "/usr/local/lib/python3.7/site-packages/pip/_internal/utils/misc.py  
", line 58, in <module>                                                       
      from typing import cast, Tuple                                          
    File "/usr/local/lib/python3.7/site-packages/typing.py", line 1357, in <  
module>                                                                       
      class Callable(extra=collections_abc.Callable, metaclass=CallableMeta)  
:                                                                             
    File "/usr/local/lib/python3.7/site-packages/typing.py", line 1005, in _  
_new__                                                                        
      self._abc_registry = extra._abc_registry                                
  AttributeError: type object 'Callable' has no attribute '_abc_registry'  
```

**Comment by sdispater** [comment]
This is on `typing-extensions` end since they should be using [environment markers](https://www.python.org/dev/peps/pep-0508/#environment-markers) instead of checking the Python version programmatically, which is discouraged.

Poetry does not execute the `setup.py` file for security reasons so it can't see it and if you take a look at https://pypi.org/pypi/typing-extensions/json you will see in the `info.requires_dist` section that `typing` is declared as an unconditional dependency.

The issue should be reported upstream and only requires to remove:

```python
install_requires = []
if sys.version_info < (3, 5):
    install_requires.append('typing >= 3.7.4')
```

and put this instead:

```python
install_requires = ["typing >= 3.7.4; python_version < '3.5'"]
```
