### ISSUE TITLE
get-poetry.py failing

### ISSUE THREAD

**Issue by robpob10** [sdispater/poetry#1286]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: CENTOS 7 
- **Poetry version**: 0.12.17 
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: n/a 

## Issue

Installation of poetry, in pipelines and on PC, fails (whereas yesterday it succeeded).
Output:

`curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python`

```
Retrieving Poetry metadata

# Welcome to Poetry!

This will download and install the latest version of Poetry,
a dependency and package manager for Python.

It will add the `poetry` command to Poetry's bin directory, located at:

$HOME/.poetry/bin

This path will then be added to your `PATH` environment variable by
modifying the profile files located at:

$HOME/.profile
$HOME/.bash_profile

You can uninstall at any time with `poetry self:uninstall`,
or by executing this script with the --uninstall option,
and these changes will be reverted.

Installing version: 0.12.17
Traceback (most recent call last):
  File "<stdin>", line 868, in <module>
  File "<stdin>", line 864, in main
  File "<stdin>", line 333, in run
  File "<stdin>", line 466, in install
  File "<stdin>", line 486, in make_lib
  File "<stdin>", line 510, in _make_lib
  File "/usr/lib64/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib64/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python2.7/urllib2.py", line 469, in error
    result = self._call_chain(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 656, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/usr/lib64/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/usr/lib64/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 1258, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/lib64/python2.7/urllib2.py", line 1214, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 104] Connection reset by peer>
```

Also fails when version is specified (tried 0.12.17 and 0.12.16), when using python3, and when on windows PC.

Problem seems to be that the `BASE_URL` (`BASE_URL = "https://github.com/sdispater/poetry/releases/download/"`) no longer exists.

**Comment by robpob10** [comment]
This problem has spontaneously gone away, so I assume it was just github problems
