### ISSUE TITLE
`poetry config` requires `pyproject.toml`?

### ISSUE THREAD

**Issue by pbzweihander** [sdispater/poetry#1296]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Arch linux
- **Poetry version**: 1.0.0b1
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: 

## Issue

```
$ poetry config -vvv

[RuntimeError]
Poetry could not find a pyproject.toml file in /home/foo or its parents

Traceback (most recent call last):
  File "/home/foo/.poetry/lib/poetry/_vendor/py3.7/clikit/console_application.py", line 132, in run
    status_code = command.handle(parsed_args, io)
  File "/home/foo/.poetry/lib/poetry/_vendor/py3.7/clikit/api/command/command.py", line 119, in handle
    status_code = self._do_handle(args, io)
  File "/home/foo/.poetry/lib/poetry/_vendor/py3.7/clikit/api/command/command.py", line 167, in _do_handle
    return getattr(handler, handler_method)(args, io, self)
  File "/home/foo/.poetry/lib/poetry/_vendor/py3.7/cleo/commands/command.py", line 92, in wrap_handle
    return self.handle()
  File "/home/foo/.poetry/lib/poetry/console/commands/config.py", line 81, in handle
    local_config_file = TomlFile(self.poetry.file.parent / 'poetry.toml')
  File "/home/foo/.poetry/lib/poetry/console/commands/command.py", line 10, in poetry
    return self.application.poetry
  File "/home/foo/.poetry/lib/poetry/console/application.py", line 55, in poetry
    self._poetry = Poetry.create(os.getcwd())
  File "/home/foo/.poetry/lib/poetry/poetry.py", line 86, in create
    poetry_file = cls.locate(cwd)
  File "/home/foo/.poetry/lib/poetry/poetry.py", line 251, in locate
    cwd
```

In the latest 1.0.0b1, `poetry config` command seems like requires `pyproject.toml` file. But I think this is a bug.

**Comment by dpraul** [comment]
Also encountering this issue

**Comment by struegamer** [comment]
Same here, this is new, and breaks the build of one of our python build images

**Comment by im-n1** [comment]
Just ran into this. This bug makes `config` command pretty much useless. Maybe it should have higher priority.

**Comment by sdispater** [comment]
It should be fixed in the latest pre-release version
