### ISSUE TITLE
poetry install error

### ISSUE THREAD

**Issue by chhantyal** [sdispater/poetry#131]
poetry looks very cool. I want to try, but can't seem to install. I am using OSX/Homebrew Python

`$ curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python`

Output: 

```
Retrieving metadata

Installing version: 0.9.1
  - Getting dependencies



An error has occured: Command '('/usr/local/bin/python', '-m', 'pip', 'install', 'poetry==0.9.1', '--target', '/var/folders/_m/4tsrnf6s703g35j636z88r_1_hlb72/T/poetry-installer-xz42dfo1/dist')' returned non-zero exit status 2.
b'Collecting poetry==0.9.1\n  Using cached https://files.pythonhosted.org/packages/7d/30/9e801da32a1453f9425061f03acb822fb9ea42f4e5de3f13aacda5564a24/poetry-0.9.1-py2.py3-none-any.whl\nCollecting requests-toolbelt<0.9.0.0,>=0.8.0.0 (from poetry==0.9.1)\n
  Using cached https://files.pythonhosted.org/packages/97/8a/d710f792d6f6ecc089c5e55b66e66c3f2f35516a1ede5a8f54c13350ffb0/requests_toolbelt-0.8.0-py2.py3-none-any.whl\nCollecting pkginfo<2.0.0.0,>=1.4.0.0 (from poetry==0.9.1)\n 
 Using cached https://files.pythonhosted.org/packages/a3/fe/f32a48d48f40a7209be9825fba2566cab92364787cf37de2e08300dd6ce7/pkginfo-1.4.2-py2.py3-none-any.whl\nCollecting cachecontrol[filecache]<0.13.0.0,>=0.12.4.0 (from poetry==0.9.1)\nCollecting pyrsistent<0.15.0.0,>=0.14.2.0 (from poetry==0.9.1)\nCollecting toml<0.10.0.0,>=0.9.0.0 (from poetry==0.9.1)\nCollecting requests<3.0.0.0,>=2.18.0.0 (from poetry==0.9.1)\n  
Using cached https://files.pythonhosted.org/packages/49/df/50aa1999ab9bde74656c2919d9c0c085fd2b3775fd3eca826012bef76d8c/requests-2.18.4-py2.py3-none-any.whl\nCollecting cachy<0.3.0.0,>=0.2.0.0 (from poetry==0.9.1)\n  Using cached https://files.pythonhosted.org/packages/26/37/8ce3e7b330078b6797a34e79a80a8ad6935e404a3b903765417182c9ce19/cachy-0.2.0-py2.py3-none-any.whl\nCollecting pyparsing<3.0.0.0,>=2.2.0.0 (from poetry==0.9.1)\n 

 Using cached https://files.pythonhosted.org/packages/6a/8a/718fd7d3458f9fab8e67186b00abdd345b639976bc7fb3ae722e1b026a50/pyparsing-2.2.0-py2.py3-none-any.whl\nCollecting pip-tools<3.0.0.0,>=2.0.0.0 (from poetry==0.9.1)\n  Using cached https://files.pythonhosted.org/packages/4c/69/4f33fea6c50ff873b7905abc404d8c26aab2accf8c099d67a35aebc09871/pip_tools-2.0.2-py2.py3-none-any.whl\nCollecting cleo<0.7.0.0,>=0.6.0.0 (from poetry==0.9.1)\n  Using cached https://files.pythonhosted.org/packages/3f/4d/fbdce6cebfdd45a6e1285b2710895661b9085dc417815b2f84f059ea8730/cleo-0.6.6-py2.py3-none-any.whl\nCollecting jsonschema<3.0.0.0,>=2.6.0.0 (from poetry==0.9.1)\n  Using cached https://files.pythonhosted.org/packages/77/de/47e35a97b2b05c2fadbec67d44cfcdcd09b8086951b331d82de90d2912da/jsonschema-2.6.0-py2.py3-none-any.whl\nCollecting msgpack-python (from cachecontrol[filecache]<0.13.0.0,>=0.12.4.0->poetry==0.9.1)\nCollecting lockfile>=0.9; extra == "filecache" (from cachecontrol[filecache]<0.13.0.0,>=0.12.4.0->poetry==0.9.1)\n  

Using cached https://files.pythonhosted.org/packages/c8/22/9460e311f340cb62d26a38c419b1381b8593b0bb6b5d1f056938b086d362/lockfile-0.12.2-py2.py3-none-any.whl\nCollecting six (from pyrsistent<0.15.0.0,>=0.14.2.0->poetry==0.9.1)\n  Using cached https://files.pythonhosted.org/packages/67/4b/141a581104b1f6397bfa78ac9d43d8ad29a7ca43ea90a2d863fe3056e86a/six-1.11.0-py2.py3-none-any.whl\nCollecting idna<2.7,>=2.5 (from requests<3.0.0.0,>=2.18.0.0->poetry==0.9.1)\n  Using cached https://files.pythonhosted.org/packages/27/cc/6dd9a3869f15c2edfab863b992838277279ce92663d334df9ecf5106f5c6/idna-2.6-py2.py3-none-any.whl\nCollecting urllib3<1.23,>=1.21.1 (from requests<3.0.0.0,>=2.18.0.0->poetry==0.9.1)\n  

Using cached https://files.pythonhosted.org/packages/63/cb/6965947c13a94236f6d4b8223e21beb4d576dc72e8130bd7880f600839b8/urllib3-1.22-py2.py3-none-any.whl\nCollecting chardet<3.1.0,>=3.0.2 (from requests<3.0.0.0,>=2.18.0.0->poetry==0.9.1)\n  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl\nCollecting certifi>=2017.4.17 (from requests<3.0.0.0,>=2.18.0.0->poetry==0.9.1)\n  

Using cached https://files.pythonhosted.org/packages/7c/e6/92ad559b7192d846975fc916b65f667c7b8c3a32bea7372340bfe9a15fa5/certifi-2018.4.16-py2.py3-none-any.whl\nCollecting click>=6 (from pip-tools<3.0.0.0,>=2.0.0.0->poetry==0.9.1)\n  Using cached https://files.pythonhosted.org/packages/34/c1/8806f99713ddb993c5366c362b2f908f18269f8d792aff1abfd700775a77/click-6.7-py2.py3-none-any.whl\nCollecting first (from pip-tools<3.0.0.0,>=2.0.0.0->poetry==0.9.1)\n  

Using cached https://files.pythonhosted.org/packages/71/12/1b24a85f543658804027de982f7e5cb80543ea33ec396c887c099c75274c/first-2.0.1-py2.py3-none-any.whl\nCollecting pastel<0.2.0,>=0.1.0 (from cleo<0.7.0.0,>=0.6.0.0->poetry==0.9.1)\n  Using cached https://files.pythonhosted.org/packages/9b/7e/7d701686013c0d7dae62e0977467232a6adc2e562c23878eb3cd4f97d02e/pastel-0.1.0-py3-none-any.whl\nCollecting pylev<2.0.0,>=1.3 (from cleo<0.7.0.0,>=0.6.0.0->poetry==0.9.1)\n  

Using cached https://files.pythonhosted.org/packages/40/1c/7dff1d242bf1e19f9c6202f0ba4e6fd18cc7ecb8bc85b17b2d16c806e228/pylev-1.3.0-py2.py3-none-any.whl\nInstalling collected packages: idna, urllib3, chardet, certifi, requests, requests-toolbelt, pkginfo, msgpack-python, lockfile, cachecontrol, six, pyrsistent, toml, cachy, pyparsing, click, first, pip-tools, pastel, pylev, cleo, jsonschema, poetry\n

Exception:\nTraceback (most recent call last):\n  File "/usr/local/Cellar/python/3.6.4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pip/_internal/basecommand.py", line 228, in main\n    status = self.run(options, args)\n  

File "/usr/local/Cellar/python/3.6.4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pip/_internal/commands/install.py", line 335, in run\n    use_user_site=options.use_user_site,\n  File "/usr/local/Cellar/python/3.6.4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pip/_internal/req/__init__.py", line 49, in install_given_reqs\n    **kwargs\n  File "/usr/local/Cellar/python/3.6.4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pip/_internal/req/req_install.py", line 748, in install\n    use_user_site=use_user_site, pycompile=pycompile,\n  File "/usr/local/Cellar/python/3.6.4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pip/_internal/req/req_install.py", line 961, in move_wheel_files\n    warn_script_location=warn_script_location,\n  File "/usr/local/Cellar/python/3.6.4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pip/_internal/wheel.py", line 216, in move_wheel_files\n    prefix=prefix,\n  File "/usr/local/Cellar/python/3.6.4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pip/_internal/locations.py", line 165, in distutils_scheme\n    i.finalize_options()\n  File "/usr/local/Cellar/python/3.6.4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/command/install.py", line 248, in finalize_options\n    "must supply either home or prefix/exec-prefix -- not both")\ndistutils.errors.DistutilsOptionError: must supply either home or prefix/exec-prefix -- not both\n'
```

**Comment by chhantyal** [comment]
Looks like this is already discussed in #59 . Closing this one.
