### ISSUE TITLE
Poetry not writing dependencies to its virtual environment

### ISSUE THREAD

**Issue by pranasziaukas** [sdispater/poetry#1361]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: 18.0.4 Manjaro Linux
- **Poetry version**: 0.12.17
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: Any

## Issue
Troubles started when I received a pip 19.2.3 update today, at least I believe so. Apparently, Poetry is not writing dependencies to its virtual environment.

For example, I `poetry init` a new project with a sole dependency of `mlflow` and do a `poetry install` which runs flawlessly (no errors or warnings whatsoever).

When I call the dependency with `poetry run mlflow ui` I get
```
Traceback (most recent call last):
  File "/home/pranas/.local/bin/mlflow", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/home/pranas/.cache/pypoetry/virtualenvs/ai.demo-py3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3191, in <module>
    @_call_aside
  File "/home/pranas/.cache/pypoetry/virtualenvs/ai.demo-py3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3175, in _call_aside
    f(*args, **kwargs)
  File "/home/pranas/.cache/pypoetry/virtualenvs/ai.demo-py3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3204, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/pranas/.cache/pypoetry/virtualenvs/ai.demo-py3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/home/pranas/.cache/pypoetry/virtualenvs/ai.demo-py3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/pranas/.cache/pypoetry/virtualenvs/ai.demo-py3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'mlflow==1.2.0' distribution was not found and is required by the application
```
That's because the virtual environment only has `pip==19.0.3` and `setuptools==40.8.0` installed (I check that using PyCharm). That's unexpected because `poetry show` shows all the (sub-)dependencies
```
alembic            1.1.0     A database migration tool for SQLAlchemy.
certifi            2019.6.16 Python package for providing Mozilla's CA Bundle.
chardet            3.0.4     Universal encoding detector for Python 2 and 3
click              7.0       Composable command line interface toolkit
...
mlflow             1.2.0     MLflow: An ML Workflow Tool
```

But `poetry remove mlflow -vvv`
```
Virtualenv ai.demo-py3.7 already exists.
Using virtualenv: /home/pranas/.cache/pypoetry/virtualenvs/ai.demo-py3.7
Updating dependencies
Resolving dependencies...
   1: fact: ai.demo is 0.1.0
   1: derived: ai.demo
   1: selecting ai.demo (0.1.0)
   1: Version solving took 0.002 seconds.
   1: Tried 1 solutions.

Writing lock file

Nothing to install or update
```
...removes nothing...

Moreover, `mlflow ui` return
```
Traceback (most recent call last):
  File "/home/pranas/.local/bin/mlflow", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/home/pranas/.cache/pypoetry/virtualenvs/ai.demo-py3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3191, in <module>
    @_call_aside
  File "/home/pranas/.cache/pypoetry/virtualenvs/ai.demo-py3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3175, in _call_aside
    f(*args, **kwargs)
  File "/home/pranas/.cache/pypoetry/virtualenvs/ai.demo-py3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3204, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/pranas/.cache/pypoetry/virtualenvs/ai.demo-py3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/home/pranas/.cache/pypoetry/virtualenvs/ai.demo-py3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/pranas/.cache/pypoetry/virtualenvs/ai.demo-py3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'mlflow==1.2.0' distribution was not found and is required by the application
```
but I believe it shouldn't have any knowledge about dependencies within a virtual environment.

Could somebody help me to make sense of all this?

**Comment by pranasziaukas** [comment]
Reproducible on a clean Manjaro installation with updated packages.

**Comment by jonathonf** [comment]
This is not a Poetry issue. Downgrade `python-pip` to the 19.0.3 package (currently in **stable**) and/or read this:

https://forum.manjaro.org/t/call-for-testing-making-pip-default-to-user/100682

**Comment by pranasziaukas** [comment]
@jonathonf Thanks for the clarification. It was not obvious to me what the culprit was.
