### ISSUE TITLE
Py3.8 incompatibility?

### ISSUE THREAD

**Issue by dimaqq** [sdispater/poetry#1376]
I had previously installed `poetry` (newest alpha) with Python 3.7.x;
I've recently upgraded to Python 3.8.0b4, and updated `/usr/local/bin/python` to point to 3.8.
After that poetry wouldn't start with:

```
… ~/zsf> poetry shell
Traceback (most recent call last):
  File "/Users/xx/.poetry/bin/poetry", line 11, in <module>
    from poetry.console import main
  File "/Users/xx/.poetry/lib/poetry/console/__init__.py", line 1, in <module>
    from .application import Application
  File "/Users/xx/.poetry/lib/poetry/console/application.py", line 7, in <module>
    from .commands import AboutCommand
  File "/Users/xx/.poetry/lib/poetry/console/commands/__init__.py", line 2, in <module>
    from .add import AddCommand
  File "/Users/xx/.poetry/lib/poetry/console/commands/add.py", line 4, in <module>
    from .init import InitCommand
  File "/Users/xx/.poetry/lib/poetry/console/commands/init.py", line 18, in <module>
    from poetry.utils.helpers import temporary_directory
  File "/Users/xx/.poetry/lib/poetry/utils/helpers.py", line 13, in <module>
    from keyring import delete_password, set_password, get_password
ModuleNotFoundError: No module named 'keyring'
```

I've since reinstalled from scratch, so sadly I can't provide any more info...
System: macOS.

**Comment by dmontagu** [comment]
I ran into this issue recently with python 3.7 on ubuntu; I remember finding it very painful to get to the bottom of the issue.

I'm pretty shaky on the details, but if I recall correctly, it was a problem where the system python had been used with the poetry installer script due to a path issue. My guess is this isn't specific to python 3.7, but maybe it was related to whether pip (or related packages) were installed in your python 3.8 environment?

**Comment by dimaqq** [comment]
Workaround:
```
pushd ~/.poetry/lib/poetry/_vendor/
cp -a py3.7 py3.8
popd
```
