### ISSUE TITLE
BadZipFile error with private repos on 1.0.0b2

### ISSUE THREAD

**Issue by dbanty** [sdispater/poetry#1483]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macOS 10.14.6
- **Poetry version**: 1.0.0b2

## Issue
I have a private repository (hosted on Gemfury) added as a source to my pyproject.toml.  When attempting to install a package from that repository with beta 2, I get an error.  It works fine with beta 1 (been using it for a while).  Full error message below, seems most similar to existing issue #155 but that's from a long time ago. 

Output of `poetry update spotr-models -vvv`

<details>

PyPI: No packages found for spotr-models >=0.2.2,<0.3.0

triaxtec: 5 packages found for spotr-models >=0.2.2,<0.3.0

PyPI: Getting info for spotr-models (0.2.6) from PyPI

triaxtec: The cache for spotr-models 0.2.6 is outdated. Refreshing.

triaxtec: Downloading wheel: spotr_models-0.2.6-py3-none-any.whl
   1: Version solving took 1.356 seconds.
   1: Tried 1 solutions.

[BadZipFile]
File is not a zip file

Traceback (most recent call last):
  File "/Users/dylan/.pyenv/versions/3.7.4/lib/python3.7/site-packages/clikit/console_application.py", line 132, in run
    status_code = command.handle(parsed_args, io)
  File "/Users/dylan/.pyenv/versions/3.7.4/lib/python3.7/site-packages/clikit/api/command/command.py", line 119, in handle
    status_code = self._do_handle(args, io)
  File "/Users/dylan/.pyenv/versions/3.7.4/lib/python3.7/site-packages/clikit/api/command/command.py", line 167, in _do_handle
    return getattr(handler, handler_method)(args, io, self)
  File "/Users/dylan/.pyenv/versions/3.7.4/lib/python3.7/site-packages/cleo/commands/command.py", line 92, in wrap_handle
    return self.handle()
  File "/Users/dylan/.pyenv/versions/3.7.4/lib/python3.7/site-packages/poetry/console/commands/update.py", line 49, in handle
    return installer.run()
  File "/Users/dylan/.pyenv/versions/3.7.4/lib/python3.7/site-packages/poetry/installation/installer.py", line 74, in run
    self._do_install(local_repo)
  File "/Users/dylan/.pyenv/versions/3.7.4/lib/python3.7/site-packages/poetry/installation/installer.py", line 161, in _do_install
    ops = solver.solve(use_latest=self._whitelist)
  File "/Users/dylan/.pyenv/versions/3.7.4/lib/python3.7/site-packages/poetry/puzzle/solver.py", line 38, in solve
    packages, depths = self._solve(use_latest=use_latest)
  File "/Users/dylan/.pyenv/versions/3.7.4/lib/python3.7/site-packages/poetry/puzzle/solver.py", line 173, in _solve
    self._package, self._provider, locked=locked, use_latest=use_latest
  File "/Users/dylan/.pyenv/versions/3.7.4/lib/python3.7/site-packages/poetry/mixology/__init__.py", line 7, in resolve_version
    return solver.solve()
  File "/Users/dylan/.pyenv/versions/3.7.4/lib/python3.7/site-packages/poetry/mixology/version_solver.py", line 79, in solve
    next = self._choose_package_version()
  File "/Users/dylan/.pyenv/versions/3.7.4/lib/python3.7/site-packages/poetry/mixology/version_solver.py", line 377, in _choose_package_version
    version = self._provider.complete_package(version)
  File "/Users/dylan/.pyenv/versions/3.7.4/lib/python3.7/site-packages/poetry/puzzle/provider.py", line 545, in complete_package
    repository=package.dependency.source_name,
  File "/Users/dylan/.pyenv/versions/3.7.4/lib/python3.7/site-packages/poetry/repositories/pool.py", line 115, in package
    package = repo.package(name, version, extras=extras)
  File "/Users/dylan/.pyenv/versions/3.7.4/lib/python3.7/site-packages/poetry/repositories/legacy_repository.py", line 293, in package
    release_info = self.get_release_info(name, version)
  File "/Users/dylan/.pyenv/versions/3.7.4/lib/python3.7/site-packages/poetry/repositories/pypi_repository.py", line 293, in get_release_info
    cached = self._get_release_info(name, version)
  File "/Users/dylan/.pyenv/versions/3.7.4/lib/python3.7/site-packages/poetry/repositories/legacy_repository.py", line 389, in _get_release_info
    info = self._get_info_from_urls(urls)
  File "/Users/dylan/.pyenv/versions/3.7.4/lib/python3.7/site-packages/poetry/repositories/pypi_repository.py", line 451, in _get_info_from_urls
    return self._get_info_from_wheel(universal_python3_wheel)
  File "/Users/dylan/.pyenv/versions/3.7.4/lib/python3.7/site-packages/poetry/repositories/pypi_repository.py", line 476, in _get_info_from_wheel
    return self._inspector.inspect_wheel(filepath)
  File "/Users/dylan/.pyenv/versions/3.7.4/lib/python3.7/site-packages/poetry/utils/inspector.py", line 56, in inspect_wheel
    meta = pkginfo.Wheel(str(file_path))
  File "/Users/dylan/.pyenv/versions/3.7.4/lib/python3.7/site-packages/pkginfo/wheel.py", line 16, in __init__
    self.extractMetadata()
  File "/Users/dylan/.pyenv/versions/3.7.4/lib/python3.7/site-packages/pkginfo/distribution.py", line 108, in extractMetadata
    data = self.read()
  File "/Users/dylan/.pyenv/versions/3.7.4/lib/python3.7/site-packages/pkginfo/wheel.py", line 24, in read
    archive = zipfile.ZipFile(fqn)
  File "/Users/dylan/.pyenv/versions/3.7.4/lib/python3.7/zipfile.py", line 1225, in __init__
    self._RealGetContents()
  File "/Users/dylan/.pyenv/versions/3.7.4/lib/python3.7/zipfile.py", line 1292, in _RealGetContents
    raise BadZipFile('File is not a zip file')
</details>

**Comment by dbanty** [comment]
This happens on 1.0.0b3 as well, same error.

**Comment by dbanty** [comment]
1.0.0b4 seems to have fixed it, must have been solved by another issue.
