### ISSUE TITLE
Error updating newer version when it's user installed

### ISSUE THREAD

**Issue by batisteo** [sdispater/poetry#154]
I tried to upgrade poetry to `0.10.1’ 

I originally install it with `pip3 --user poetry` (Python 3.6.5)

```bash
$ poetry --version
Poetry 0.9.1

$ poetry self:update
Updating to 0.10.1
  - Getting dependencies
  - Vendorizing dependencies
  - Updating poetry

 [CalledProcessError]
 An error has occured: Command '['/usr/bin/pip', 'install', '--upgrade', '--no-deps', '/tmp/poetry-update-

 FShfiE/poetry-0.10.1-py2.py3-none-any.whl']' returned non-zero exit status 2

 Processing /tmp/poetry-update-FShfiE/poetry-0.10.1-py2.py3-none-any.whl Installing collected packages: poetry   Found
 existing installation: poetry 0.9.1
 Uninstalling poetry-0.9.1:
   Successfully uninstalled poetry-0.9.1
```

```python
 Rolling back uninstall of poetry Exception: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/site-packages/pip/commands/install.py", line 365, in run
    strip_file_prefix=options.strip_file_prefix,
  File "/usr/lib/python2.7/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/usr/lib/python2.7/site-packages/pip/req/req_install.py", line 854, in install
    strip_file_prefix=strip_file_prefix
  File "/usr/lib/python2.7/site-packages/pip/req/req_install.py", line 1069, in move_wheel_files
    strip_file_prefix=strip_file_prefix,
  File "/usr/lib/python2.7/site-packages/pip/wheel.py", line 345, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/usr/lib/python2.7/site-packages/pip/wheel.py", line 316, in clobber
    ensure_dir(destdir)
  File "/usr/lib/python2.7/site-packages/pip/utils/__init__.py", line 83, in ensure_dir
    os.makedirs(path)
  File "/usr/lib64/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode) OSError: [Errno 13] Permission denied: '/usr/lib/python2.7/site-packages/poetry-0.10.1.dist-info'
```

**Comment by sdispater** [comment]
Yes, there is a lot of improvement to be done in the `self:update` command, especially detecting if poetry has been installed with `--user`.

**Comment by sdispater** [comment]
The new installer and the improved `self:update` command should fix this.
