### ISSUE TITLE
Poetry fails to install idna-ssl dependency with Wine: "ValueError: illegal environment variable name"

### ISSUE THREAD

**Issue by desbma** [sdispater/poetry#157]
The context is similar to issue #147 (Wine on Linux), but I get a different error, when having no virtualenv enabled (the cause of #147), and when installing a particular package, `idna-ssl`:

```
Creating virtualenv whatever-py3.6 in C:\users\desbma\Local Settings\Application Data\pypoetry\Cache\virtualenvs
Using virtualenv: C:\users\desbma\Local Settings\Application Data\pypoetry\Cache\virtualenvs\whatever-py3.6
Updating dependencies
Resolving dependencies... (0.8s)


Package operations: 2 installs, 0 updates, 0 removals

Writing lock file

  - Installing idna (2.6)
  - Installing idna-ssl (1.0.1)
                                                                                
[VenvCommandError]                                               
Command ['pip', 'install', '--no-deps', '-r', 'C:\\users\\desbma\\Temp\\idna  
-ssl-1.0.1mbmbbw6xreqs.txt'] errored with the following output:               
Collecting idna-ssl==1.0.1 (from -r C:\users\desbma\Temp\idna-ssl-1.0.1mbmbb  
w6xreqs.txt (line 1))                                                         
  Downloading https://files.pythonhosted.org/packages/c4/3b/facf5a5009e577e7  
764e68a2af5ee25c63f41c78277260c2c42b8cfabf2e/idna-ssl-1.0.1.tar.gz            
    Error illegal environment variable name while executing command python s  
etup.py egg_info                                                              
Exception:                                                                    
Traceback (most recent call last):                                            
  File "c:\users\desbma\local settings\application data\pypoetry\Cache\virtu  
alenvs\whatever-py3.6\lib\site-packages\pip\basecommand.py", line 215, in ma  
in                                                                            
    status = self.run(options, args)                                          
  File "c:\users\desbma\local settings\application data\pypoetry\Cache\virtu  
alenvs\whatever-py3.6\lib\site-packages\pip\commands\install.py", line 324,   
in run                                                                        
    requirement_set.prepare_files(finder)                                     
  File "c:\users\desbma\local settings\application data\pypoetry\Cache\virtu  
alenvs\whatever-py3.6\lib\site-packages\pip\req\req_set.py", line 380, in pr  
epare_files                                                                   
    ignore_dependencies=self.ignore_dependencies))                            
  File "c:\users\desbma\local settings\application data\pypoetry\Cache\virtu  
alenvs\whatever-py3.6\lib\site-packages\pip\req\req_set.py", line 634, in _p  
repare_file                                                                   
    abstract_dist.prep_for_dist()                                             
  File "c:\users\desbma\local settings\application data\pypoetry\Cache\virtu  
alenvs\whatever-py3.6\lib\site-packages\pip\req\req_set.py", line 129, in pr  
ep_for_dist                                                                   
    self.req_to_install.run_egg_info()                                        
  File "c:\users\desbma\local settings\application data\pypoetry\Cache\virtu  
alenvs\whatever-py3.6\lib\site-packages\pip\req\req_install.py", line 439, i  
n run_egg_info                                                                
    command_desc='python setup.py egg_info')                                  
  File "c:\users\desbma\local settings\application data\pypoetry\Cache\virtu  
alenvs\whatever-py3.6\lib\site-packages\pip\utils\__init__.py", line 667, in  
 call_subprocess                                                              
    cwd=cwd, env=env)                                                         
  File "c:\Python36\lib\subprocess.py", line 709, in __init__                 
    restore_signals, start_new_session)                                       
  File "c:\Python36\lib\subprocess.py", line 997, in _execute_child           
    startupinfo)                                                              
ValueError: illegal environment variable name                                 
You are using pip version 9.0.1, however version 10.0.1 is available.         
You should consider upgrading via the 'python -m pip install --upgrade pip'   
command.                                                                      
                                                                                
Exception trace:
 c:\Python36\lib\site-packages\poetry\_vendor\cleo\application.py in run() at line 94
   status_code = self.do_run(input_, output_)
 c:\Python36\lib\site-packages\poetry\console\application.py in do_run() at line 86
   return super(Application, self).do_run(i, o)
 c:\Python36\lib\site-packages\poetry\_vendor\cleo\application.py in do_run() at line 197
   status_code = command.run(input_, output_)
 c:\Python36\lib\site-packages\poetry\console\commands\command.py in run() at line 77
   return super(BaseCommand, self).run(i, o)
 c:\Python36\lib\site-packages\poetry\_vendor\cleo\commands\base_command.py in run() at line 146
   status_code = self.execute(input_, output_)
 c:\Python36\lib\site-packages\poetry\_vendor\cleo\commands\command.py in execute() at line 107
   return self.handle()
 c:\Python36\lib\site-packages\poetry\console\commands\install.py in handle() at line 52
   return installer.run()
 c:\Python36\lib\site-packages\poetry\installation\installer.py in run() at line 75
   self._do_install(local_repo)
 c:\Python36\lib\site-packages\poetry\installation\installer.py in _do_install() at line 257
   self._execute(op)
 c:\Python36\lib\site-packages\poetry\installation\installer.py in _execute() at line 265
   getattr(self, '_execute_{}'.format(method))(operation)
 c:\Python36\lib\site-packages\poetry\installation\installer.py in _execute_install() at line 291
   self._installer.install(operation.package)
 c:\Python36\lib\site-packages\poetry\installation\pip_installer.py in install() at line 38
   self.run(*args)
 c:\Python36\lib\site-packages\poetry\installation\pip_installer.py in run() at line 63
   return self._venv.run('pip', *args, **kwargs)
 c:\Python36\lib\site-packages\poetry\utils\venv.py in run() at line 279
   raise VenvCommandError(e)

install [--no-dev] [--dry-run] [-E|--extras EXTRAS] [--develop DEVELOP]
```

Standalone script to reproduce: https://pastebin.com/raw/UNu9JL8g

The same dependency gets installed normally using Poetry on Linux, or pip on Wine.

**Comment by sdispater** [comment]
`ValueError: illegal environment variable name` indicates that there is something wrong in one of your environment variables.

Could you show what they look like when installing with poetry inside Wine?

**Comment by desbma** [comment]
```
$ wine /tmp/tmp.XVEpIymW8O/drive_c/Python36/python.exe -c 'import os; print(os.environ)'
environ({'VIRTUALENVWRAPPER_WORKON_CD': '0', 'VIRTUALENVWRAPPER_HOOK_DIR': '/home/desbma/py-venvs', 'LANG': 'fr_FR.utf8', 'GDM_LANG': 'fr_FR.utf8', 'DISPLAY': ':0', 'OLDPWD': '/home/desbma/Desktop', 'WORKON_HOME': '/home/desbma/py-venvs', 'GTK_OVERLAY_SCROLLING': '1', 'COLORTERM': 'truecolor', 'MOZ_PLUGIN_PATH': '/usr/lib/mozilla/plugins', 'XDG_VTNR': '7', 'SSH_AUTH_SOCK': '/run/user/1000/keyring/ssh', 'HG': '/usr/bin/hg', 'XDG_SESSION_ID': 'c1', 'XDG_GREETER_DATA_DIR': '/var/lib/lightdm-data/desbma', 'USER': 'desbma', 'DESKTOP_SESSION': 'cinnamon', 'GNOME_TERMINAL_SCREEN': '/org/gnome/Terminal/screen/514c1615_78db_4075_bc4f_a8a0e9064450', 'XDG_SESSION_TYPE': 'x11', 'XDG_SESSION_DESKTOP': 'cinnamon', 'WINEDEBUG': '-all', 'GJS_DEBUG_OUTPUT': 'stderr', 'GTK_MODULES': 'canberra-gtk-module', 'MAIL': '/var/spool/mail/desbma', 'VIRTUALENVWRAPPER_SCRIPT': '/usr/bin/virtualenvwrapper.sh', 'TERM': 'xterm-256color', 'SHELL': '/bin/zsh', 'VTE_VERSION': '5202', 'XDG_SEAT_PATH': '/org/freedesktop/DisplayManager/Seat0', 'XDG_CURRENT_DESKTOP': 'X-Cinnamon', 'GNOME_TERMINAL_SERVICE': ':1.83', 'XDG_SEAT': 'seat0', 'SHLVL': '2', 'GDMSESSION': 'cinnamon', 'GNOME_DESKTOP_SESSION_ID': 'this-is-deprecated', 'LOGNAME': 'desbma', 'DBUS_SESSION_BUS_ADDRESS': 'unix:path=/run/user/1000/bus', 'XDG_RUNTIME_DIR': '/run/user/1000', 'XAUTHORITY': '/home/desbma/.Xauthority', 'VIRTUALENVWRAPPER_PROJECT_FILENAME': '.project', 'XDG_SESSION_PATH': '/org/freedesktop/DisplayManager/Session0', 'CINNAMON_VERSION': '3.8.3', 'GJS_DEBUG_TOPICS': 'JS ERROR;JS LOG', 'SESSION_MANAGER': 'local/INI7:@/tmp/.ICE-unix/835,unix/INI7:/tmp/.ICE-unix/835', 'WINEPREFIX': '/tmp/tmp.DltijykrRa', '_': '/usr/bin/wine', 'WINELOADERNOEXEC': '1', 'NUMBER_OF_PROCESSORS': '12', 'OS': 'Windows_NT', 'PATHEXT': '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH', 'PROCESSOR_ARCHITECTURE': 'AMD64', 'PROCESSOR_IDENTIFIER': 'AMD64 Family 6 Model 44 Stepping 2, GenuineIntel', 'PROCESSOR_LEVEL': '6', 'PROCESSOR_REVISION': '2c02', 'SYSTEMDRIVE': 'c:', 'SYSTEMROOT': 'C:\\windows', 'WINSYSDIR': 'C:\\windows\\system32', 'COMSPEC': 'C:\\windows\\system32\\cmd.exe', 'PATH': 'C:\\windows\\system32;C:\\windows;C:\\windows\\system32\\wbem', 'TEMP': 'C:\\users\\desbma\\Temp', 'TMP': 'C:\\users\\desbma\\Temp', 'WINDIR': 'C:\\windows', 'APPDATA': 'C:\\users\\desbma\\Application Data', 'CLIENTNAME': 'Console', 'HOMEDRIVE': 'C:', 'HOMEPATH': '\\users\\desbma', 'LOCALAPPDATA': 'C:\\users\\desbma\\Local Settings\\Application Data', 'LOGONSERVER': '\\\\INI7', 'SESSIONNAME': 'Console', 'USERDOMAIN': 'INI7', 'USERNAME': 'desbma', 'USERPROFILE': 'C:\\users\\desbma', 'COMPUTERNAME': 'INI7', 'ALLUSERSPROFILE': 'C:\\users\\Public', 'PROGRAMDATA': 'C:\\ProgramData', 'PROGRAMW6432': 'C:\\Program Files', 'PROGRAMFILES': 'C:\\Program Files', 'COMMONPROGRAMW6432': 'C:\\Program Files\\Common Files', 'COMMONPROGRAMFILES': 'C:\\Program Files\\Common Files'})
```

Again there is a mix of Linux and Wine environment variables here which could explain the issue, but why does raw pip handle it fine and not Poetry?

**Comment by desbma** [comment]
I tried to run Wine with `env -i ` to clear all host environment variables, but Wine does not even start in that case.

**Comment by stuaxo** [comment]
Maybe this is just my setup, but I seem to have an env var whose name is an empty string
```
>>> import os
>>> os.environ['']
'Z:=Z:\\home\\stu\\Downloads'
```

I added the line ```env.pop('')``` to ```~/.wine/drive_c/Python27/Lib/site-packages/pip/_internal/utils/misc.py```

after:

```
    env = os.environ.copy()
    if extra_environ:
        env.update(extra_environ)
```

And pip seems to get quite a bit further for my own library, it might help here too.

**Comment by sdispater** [comment]
Similar to what I mentioned #147 this use case is not officially supported so closing this.

**Comment by stuaxo** [comment]
I've opened a Wine bug for this
https://bugs.winehq.org/show_bug.cgi?id=46108

It's a bit of a weird edge case so I've opened a PR against pip to remove the environment variable named as an empty space, enabling it to work.

https://github.com/pypa/pip/pull/6315

**Comment by desbma** [comment]
@stuaxo I am not sure this is related.
In https://github.com/sdispater/poetry/issues/157#issuecomment-393323983 you can see I did not have an empty varibale like you.
Now I can not reproduce this issue (everything seems to work).

#147 (same Wine environement but without disabling Linux virtualenv) is not fixed though. Now I get a JSONDecodeError` exception, but this is the same encoding root cause.

**Comment by stuaxo** [comment]
Apologies for the noise, came across this through googling, should have read your env vars.
