### ISSUE TITLE
poetry show -o is broken

### ISSUE THREAD

**Issue by bertjwregeer** [sdispater/poetry#1605]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macOS
- **Poetry version**: 1.0.0b5

## Issue

```
Riley ~/Projects/APPA/account-new % poetry show -o -vvv
Using virtualenv: /Users/xistence/Projects/APPA/account-new/.venv

[ValueError]
'=' alignment not allowed in string format specifier

Traceback (most recent call last):
  File "/Users/xistence/.ve/poetry/lib/python3.8/site-packages/clikit/console_application.py", line 131, in run
    status_code = command.handle(parsed_args, io)
  File "/Users/xistence/.ve/poetry/lib/python3.8/site-packages/clikit/api/command/command.py", line 120, in handle
    status_code = self._do_handle(args, io)
  File "/Users/xistence/.ve/poetry/lib/python3.8/site-packages/clikit/api/command/command.py", line 171, in _do_handle
    return getattr(handler, handler_method)(args, io, self)
  File "/Users/xistence/.ve/poetry/lib/python3.8/site-packages/cleo/commands/command.py", line 92, in wrap_handle
    return self.handle()
  File "/Users/xistence/.ve/poetry/lib/python3.8/site-packages/poetry/console/commands/show.py", line 175, in handle
    line = "<fg={}>{:{}}{}".format(
```

**Comment by oakkitten** [comment]
duplicate of #1323

**Comment by bertjwregeer** [comment]
You are correct!
