### ISSUE TITLE
Installing allennlp from GitHub results in a RuntimeError

### ISSUE THREAD

**Issue by willfrey** [sdispater/poetry#1678]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macOS Catalina Version 10.15.1
- **Poetry version**: 1.0.0b8

## Issue
I'm struggling to install [AllenNLP](https://github.com/allenai/allennlp) directly from GitHub but I am receiving a runtime error.

The following snippet should reproduce the error assuming that `python3` on your path points to Python 3.7.

```console
$ cd /tmp
$ poetry new pkg
Created package pkg in pkg
$ cd pkg
$ poetry env use python3
Creating virtualenv pkg-i7QhwukE-py3.7 in /Users/will.frey/Library/Caches/pypoetry/virtualenvs
Using virtualenv: /Users/will.frey/Library/Caches/pypoetry/virtualenvs/pkg-i7QhwukE-py3.7
$ poetry add -vvv "git+https://github.com/allenai/allennlp"
Using virtualenv: /Users/will.frey/Library/Caches/pypoetry/virtualenvs/pkg-i7QhwukE-py3.7

[RuntimeError]
The Poetry configuration is invalid:
  - 'version' is a required property
  - 'description' is a required property


Traceback (most recent call last):
  File "/Users/will.frey/.poetry/lib/poetry/_vendor/py3.7/clikit/console_application.py", line 131, in run
    status_code = command.handle(parsed_args, io)
  File "/Users/will.frey/.poetry/lib/poetry/_vendor/py3.7/clikit/api/command/command.py", line 120, in handle
    status_code = self._do_handle(args, io)
  File "/Users/will.frey/.poetry/lib/poetry/_vendor/py3.7/clikit/api/command/command.py", line 171, in _do_handle
    return getattr(handler, handler_method)(args, io, self)
  File "/Users/will.frey/.poetry/lib/poetry/_vendor/py3.7/cleo/commands/command.py", line 92, in wrap_handle
    return self.handle()
  File "/Users/will.frey/.poetry/lib/poetry/console/commands/add.py", line 89, in handle
    packages, allow_prereleases=self.option('allow-prereleases')
  File "/Users/will.frey/.poetry/lib/poetry/console/commands/init.py", line 294, in _determine_requirements
    requires = self._parse_requirements(requires)
  File "/Users/will.frey/.poetry/lib/poetry/console/commands/init.py", line 382, in _parse_requirements
    "git", url.url, reference=pair.get("rev")
  File "/Users/will.frey/.poetry/lib/poetry/puzzle/provider.py", line 204, in get_package_from_vcs
    package = cls.get_package_from_directory(tmp_dir, name=name)
  File "/Users/will.frey/.poetry/lib/poetry/puzzle/provider.py", line 305, in get_package_from_directory
    poetry = Factory().create_poetry(directory)
  File "/Users/will.frey/.poetry/lib/poetry/factory.py", line 54, in create_poetry
    raise RuntimeError('The Poetry configuration is invalid:
'" + message)
```

I am able to install their most recent release by specifying the tag

```console
poetry add "git+https://github.com/allenai/allennlp@v0.9.0"
```

so perhaps this is just a problem with the way that the master branch is configured.

I am also able to install the master branch if I clone it and create my own wheel file and specify the path to the wheel instead of the GitHub repo.

Any idea what's going on here?

Thank you!

**Comment by finswimmer** [comment]
Hello @willfrey ,

the master branch contains a `pyproject.toml` which also includes a `tool.poetry` section. So poetry tries to install the package based on that `pyproject.toml`. But the file is not valid, as it doesn't contains the mandatory keys like `version` and `description`. That's why the installation fails.

The release with the tag, doesn't have a `pyproject.toml`, so poetry chooses the `setup.py` and is able to install.

Please report  that to the maintainers of AllenNLP.

Thanks!

fin swimmer

**Comment by willfrey** [comment]
Thanks for diagnosing that! I'll open an issue on the AllenNLP repo.
