### ISSUE TITLE
[TypeError] distributions() got an unexpected keyword argument 'path'

### ISSUE THREAD

**Issue by earshinov** [sdispater/poetry#1691]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version (poetry 1.0.0b9)
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I executed the failing command in debug mode (`-vvv` option).

Version information:
- CentOS Linux release 7.6.1810 (running in a virtual machine)
- Python 3.6.5
- Poetry 1.0.0b9
- [project.toml](https://gist.github.com/earshinov/ea3090d658541b61360dd17ed6c8b2f4)

## Issue

Hi, I am just trying out Poetry, and I think I have found a bug in Python version compatibility layer:

```
$  poetry install -vvv

Using virtualenv: /home/vagrant/secret

[TypeError]
distributions() got an unexpected keyword argument 'path'

Traceback (most recent call last):
  File "/home/vagrant/secret/lib64/python3.6/site-packages/clikit/console_application.py", line 131, in run
    status_code = command.handle(parsed_args, io)
  File "/home/vagrant/secret/lib64/python3.6/site-packages/clikit/api/command/command.py", line 120, in handle
    status_code = self._do_handle(args, io)
  File "/home/vagrant/secret/lib64/python3.6/site-packages/clikit/api/command/command.py", line 171, in _do_handle
    return getattr(handler, handler_method)(args, io, self)
  File "/home/vagrant/secret/lib64/python3.6/site-packages/cleo/commands/command.py", line 92, in wrap_handle
    return self.handle()
  File "/home/vagrant/secret/lib64/python3.6/site-packages/poetry/console/commands/install.py", line 48, in handle
    self.io, self.env, self.poetry.package, self.poetry.locker, self.poetry.pool
  File "/home/vagrant/secret/lib64/python3.6/site-packages/poetry/installation/installer.py", line 55, in __init__
    installed = self._get_installed()
  File "/home/vagrant/secret/lib64/python3.6/site-packages/poetry/installation/installer.py", line 488, in _get_installed
    return InstalledRepository.load(self._env)
  File "/home/vagrant/secret/lib64/python3.6/site-packages/poetry/repositories/installed_repository.py", line 20, in load
    metadata.distributions(path=env.sys_path), key=lambda d: str(d._path),
```

Under inspection, `inspect_metadata.metadata.distributions` indeed does not have the `path` kwarg:

```
$ python
Python 3.6.5 (default, Apr 10 2018, 17:08:37) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-16)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import importlib_metadata as metadata
>>> import inspect
>>> print(inspect.getsource(metadata.distributions))
def distributions():
    """Get all ``Distribution`` instances in the current environment.

    :return: An iterable of ``Distribution`` instances.
    """
    return Distribution.discover()
```

**Comment by earshinov** [comment]
Sorry, I did not realize that import-metadata is a third-party package. For some reason I had import-metadata==0.20. Technically it satisfies the requirements, but does not work, as you can see. Running `poetry update import-metadata` installed import-metadata==1.2.0 and fixed the issue.
