### ISSUE TITLE
Better user experience for keyboard interrupts

### ISSUE THREAD

**Issue by playpauseandstop** [sdispater/poetry#19]
When running web server (or other daemon-like process) via `poetry run`, like `aiohttp.web.run_app` stopping it with `Ctrl+C` leads to redundant traceback, like:

```
$ poetry run python -m api
======== Running on http://0.0.0.0:8205 ========
(Press CTRL+C to quit)
======== Running on http://0.0.0.0:8205 ========
(Press CTRL+C to quit)
^CTraceback (most recent call last):
  File "/Users/playpauseandstop/.pyenv/versions/3.6.4/bin/poetry", line 11, in <module>
    sys.exit(console.run())
  File "/Users/playpauseandstop/.pyenv/versions/3.6.4/lib/python3.6/site-packages/poetry/console/application.py", line 59, in run
    return super().run(i, o)
  File "/Users/playpauseandstop/.pyenv/versions/3.6.4/lib/python3.6/site-packages/cleo/application.py", line 94, in run
    status_code = self.do_run(input_, output_)
  File "/Users/playpauseandstop/.pyenv/versions/3.6.4/lib/python3.6/site-packages/poetry/console/application.py", line 70, in do_run
    status_code = command.run(i, o)
  File "/Users/playpauseandstop/.pyenv/versions/3.6.4/lib/python3.6/site-packages/poetry/console/commands/command.py", line 25, in run
    return super(BaseCommand, self).run(i, o)
  File "/Users/playpauseandstop/.pyenv/versions/3.6.4/lib/python3.6/site-packages/cleo/commands/base_command.py", line 146, in run
    status_code = self.execute(input_, output_)
  File "/Users/playpauseandstop/.pyenv/versions/3.6.4/lib/python3.6/site-packages/cleo/commands/command.py", line 108, in execute
    return self.handle()
  File "/Users/playpauseandstop/.pyenv/versions/3.6.4/lib/python3.6/site-packages/poetry/console/commands/run.py", line 17, in handle
    return venv.exec(*args)
  File "/Users/playpauseandstop/.pyenv/versions/3.6.4/lib/python3.6/site-packages/poetry/utils/venv.py", line 167, in exec
    completed = subprocess.run([bin] + list(args), **kwargs)
  File "/Users/playpauseandstop/.pyenv/versions/3.6.4/lib/python3.6/subprocess.py", line 405, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/Users/playpauseandstop/.pyenv/versions/3.6.4/lib/python3.6/subprocess.py", line 835, in communicate
    self.wait()
  File "/Users/playpauseandstop/.pyenv/versions/3.6.4/lib/python3.6/subprocess.py", line 1457, in wait
    (pid, sts) = self._try_wait(0)
  File "/Users/playpauseandstop/.pyenv/versions/3.6.4/lib/python3.6/subprocess.py", line 1404, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
KeyboardInterrupt
```

From my POV, the keyboard interrupt traceback should be omitted as it is a kind of expected error for `poetry run ...` calls.

----

Source of `api/__main__.py` is listed below,

<details>
```py
import asyncio

import uvloop
from aiohttp import web

from api.app import create_app


if __name__ == '__main__':
    asyncio.set_event_loop_policy(uvloop.EventLoopPolicy())

    app = create_app()
    if app['settings']['DEBUG']:
        import aiohttp_autoreload
        aiohttp_autoreload.start()

    web.run_app(app, host='0.0.0.0', port=8205)
```
</details>

**Comment by sdispater** [comment]
This is now implemented in the latest versions :-)

**Comment by bertjwregeer** [comment]
Instead of using subprocess.run and communicating back and forth, it may make more sense for poetry to just `execve`, unless on Windows, see my project `vrun` which can be used with virtualenvs to setup the environment correctly/set `$PATH`:

https://github.com/bertjwregeer/vrun/blob/master/src/vrun/oscompat.py

This way you don't have a python process that runs unnecessarily, and there is less chance of dealing with terminal issues (think ncurses and other such things).
