### ISSUE TITLE
poetry breaks if config.toml is invalid

### ISSUE THREAD

**Issue by xsduan** [sdispater/poetry#192]
```toml
[settings]

[repositories]
artifactory = {url = """
http://<snip>/pypi/pypi-virtual/simple
"""}
```

```
Traceback (most recent call last):
  File "c:\<snip>\python\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\<snip>\python\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\<snip>\Python\Python36\Scripts\poetry.exe\__main__.py", line 9, in <module>
  File "c:\<snip>\python\python36\lib\site-packages\poetry\console\__init__.py", line 5, in main
    return Application().run()
  File "c:\<snip>\python\python36\lib\site-packages\poetry\console\application.py", line 45, in __init__
    super(Application, self).__init__("Poetry", __version__)
  File "c:\<snip>\python\python36\lib\site-packages\cleo\application.py", line 66, in __init__
    for command in self.get_default_commands():
  File "c:\<snip>\python\python36\lib\site-packages\poetry\console\application.py", line 111, in get_default_commands
    ConfigCommand(),
  File "c:\<snip>\python\python36\lib\site-packages\poetry\console\commands\config.py", line 43, in __init__
    self._config = Config.create("config.toml")
  File "c:\<snip>\python\python36\lib\site-packages\poetry\config.py", line 92, in create
    return cls(file)
  File "c:\<snip>\python\python36\lib\site-packages\poetry\config.py", line 16, in __init__
    self._raw_content = file.read(raw=True)
  File "c:\<snip>\python\python36\lib\site-packages\poetry\utils\toml_file.py", line 22, in read
    return toml.loads(f.read())
  File "c:\<snip>\python\python36\lib\site-packages\toml.py", line 373, in loads
    multibackslash)
  File "c:\<snip>\python\python36\lib\site-packages\toml.py", line 479, in _load_line
    value, vtype = _load_value(pair[1], _dict, strictly_valid)
  File "c:\<snip>\python\python36\lib\site-packages\toml.py", line 639, in _load_value
    _load_inline_object(v, inline_object, _dict)
  File "c:\<snip>\python\python36\lib\site-packages\toml.py", line 399, in _load_inline_object
    candidate_groups[0] = candidate_group + "," + candidate_groups[0]
IndexError: list index out of range
```

I ran `poetry config repositories.artifactory "<the url>"` and somehow it encoded the config.toml file in a way that couldn't be reparsed.

I am unable to unset the key, and no indication was given to the actual filepath of config.toml. I've tried reinstalling poetry (i guess to reset the files or something) and nothing other than actually editing config.toml manually will fix it.

I don't know what the solution would be, if it would be better to delete the toml, ignore the config, or exit with a helpful warning. In the meantime:

```py
    def read(self, raw=False):  # type: (bool) -> dict
        with self._path.open() as f:
            if raw:
                try:
                    return toml.loads(f.read())
                except Exception e:
                    raise ParseError('Could not parse config.toml') from e 

            return loads(f.read())
```

Edit: I should probably add my environment.

- Windows 10
- Python 3.6.5 (x64 64-bit)
- pip 10.0.1
- poetry 0.10.3

**Comment by sdispater** [comment]
Thanks for reporting this!

While there is definitely a bug when adding a repository like you mentionned, I also agree that the `config` should be smarter in how it handles error and check the  validity of the TOML file before writing it back

**Comment by xsduan** [comment]
Idk if this should go in a new issue or not but I figured out that it's writing an invalid toml file because of backslashes. (apparently I accidentally fudged a backslash while trying to press enter when typing the example)

```toml
[settings]

[repositories]
oopsies = {url = "http://google.com/\"}
oopsies_two = {url = """
https://cas.pacific.edu/cas/login?service=https%3A%2F%2Flum-prod.ec.pacific.edu%2Fc%2Fportal%2Flogin\\
"""}
```

```bash
$ poetry config repositories.oopsies "http://google.com/\"
$ poetry config --all
# python stack trace...

$ poetry config repositories.oopsies_two "https://cas.pacific.edu/cas/login?service=https%3A%2F%2Flum-prod.ec.pacific.edu%2Fc%2Fportal%2Flogin\"
$ poetry config --all
# python stack trace...
```

I haven't really bothered to check the location where it's writing the toml, but if it's writing using toml.dumps() (or whatever it uses, I haven't checked), then it's a problem with the toml package.

**Comment by sdispater** [comment]
This should be fixed in the latest release with the introduction of a new TOML library: [TOML Kit](https://github.com/sdispater/tomlkit)
