### ISSUE TITLE
Verbose flag causes error

### ISSUE THREAD

**Issue by cauebs** [sdispater/poetry#200]
No matter which command I run (although I haven't tried all of them), if I include the `--verbose` flag, I get the following error:

```
~ $ poetry new foo --verbose
Traceback (most recent call last):
  File "/home/cauebs/.local/bin/poetry", line 11, in <module>
    sys.exit(main())
  File "/home/cauebs/.local/lib/python3.6/site-packages/poetry/console/__init__.py", line 5, in main
    return Application().run()
  File "/home/cauebs/.local/lib/python3.6/site-packages/poetry/console/application.py", line 81, in run
    return super(Application, self).run(i, o)
  File "/home/cauebs/.local/lib/python3.6/site-packages/poetry/_vendor/cleo/application.py", line 91, in run
    self.configure_io(input_, output_)
  File "/home/cauebs/.local/lib/python3.6/site-packages/poetry/console/application.py", line 101, in configure_io
    super(Application, self).configure_io(i, o)
  File "/home/cauebs/.local/lib/python3.6/site-packages/poetry/_vendor/cleo/application.py", line 511, in configure_io
    or input_.get_parameter_option('--verbose') == 3:
  File "/home/cauebs/.local/lib/python3.6/site-packages/poetry/_vendor/cleo/inputs/argv_input.py", line 202, in get_parameter_option
    return tokens.pop(0)
IndexError: pop from empty list
```

**Comment by cauebs** [comment]
Oh, that was very naïve of me. It seems the problem is up on cleo. Do you want me to reopen this issue there?
