### ISSUE TITLE
How do I include a dash in the project name?

### ISSUE THREAD

**Issue by jacebrowning** [sdispater/poetry#285]
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://poetry.eustace.io/docs/) and believe that my question is not covered.

## Question

The Python package for https://pypi.org/project/coverage-space/ is named `coveragespace`.

With `name = "coverage-space"` in `pyproject.tml`, Poetry reports:

```
$ poetry develop

[ValueError]
No file/folder found for package coverage-space

develop
```

**Comment by jacebrowning** [comment]
Similarly, with this dependency:

 ```
coverage-space = { git = "https://github.com/jacebrowning/coverage-space-cli", rev = "8b695a1711cb7f7273aa79b1415756ca58f04e3b" }
```

Poetry reports:

```
$ poetry lock
Updating dependencies
Resolving dependencies... (0.5s)

[RuntimeError]
The dependency name for coverage-space does not match the actual package's name: coveragespace

lock
```

**Comment by sdispater** [comment]
The second error comes from #259 and is expected. This is due to how the resolver works. There is no way around it at the moment. So to fix it you will have to put:

```toml
coveragespace = { git = "https://github.com/jacebrowning/coverage-space-cli", rev = "8b695a1711cb7f7273aa79b1415756ca58f04e3b" }
```

in you `pyproject.toml` file

**Comment by jacebrowning** [comment]
FWIW, I (predictably?) get `FileNotFoundError` when using a Poetry project as a Git depenency:

```
$ poetry develop
Installing dependencies from lock file


Package operations: 1 install, 0 updates, 0 removals

  - Installing coveragespace (1.0.1a2 8b695a1)

[VenvCommandError]
Command ['pip', 'install', '--no-deps', 'git+https://github.com/jacebrowning/coverage-space-cli@8b695a1711cb7f7273aa79b1415756ca58f04e3b#egg=coveragespace'] errored with the fol
lowing output:
Collecting coveragespace from git+https://github.com/jacebrowning/coverage-space-cli@8b695a1711cb7f7273aa79b1415756ca58f04e3b#egg=coveragespace
  Cloning https://github.com/jacebrowning/coverage-space-cli (to revision 8b695a1711cb7f7273aa79b1415756ca58f04e3b) to /private/var/folders/h1/2b6gts3x37zcnj5khyv8y5180000gn/T/p
ip-install-b_2kqsv7/coveragespace
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/Users/Browning/.pyenv/versions/3.7.0/lib/python3.7/tokenize.py", line 447, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/private/var/folders/h1/2b6gts3x37zcnj5khyv8y5180000gn/T/pip-install-b_2kqsv7/coveragespace/setup.py'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/h1/2b6gts3x37zcnj5khyv8y5180000gn/T/pip-install-b_2kqsv7/coveragespace/

develop
```

**Comment by sdispater** [comment]
This should now be fixed.
