### ISSUE TITLE
poetry fails if config value contains un-escaped backslashes

### ISSUE THREAD

**Issue by CrossR** [sdispater/poetry#396]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Windows 10 Pro 64Bit
- **Poetry version**: 0.11.4
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: N/A

## Issue

It looks like if a config value is set with `\` that is not escaped, `poetry` will not run at all.
That is, I did this using the tab complete in Windows CMD.

```batch
poetry config settings.virtualenvs.path "C:\Users\Ryan\.virtualenvs"
```

No reported errors (with or without `-vvv`). However, running any `poetry` command after then fails.
This is `poetry -V`:

```
Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\programdata\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Ryan\AppData\Roaming\Python\Python36\Scripts\poetry.exe\__main__.py", line 9, in <module>
  File "C:\Users\Ryan\AppData\Roaming\Python\Python36\site-packages\poetry\console\__init__.py", line 5, in main
    return Application().run()
  File "C:\Users\Ryan\AppData\Roaming\Python\Python36\site-packages\poetry\console\application.py", line 46, in __init__
    super(Application, self).__init__("Poetry", __version__)
  File "c:\programdata\anaconda3\lib\site-packages\cleo\application.py", line 66, in __init__
    for command in self.get_default_commands():
  File "C:\Users\Ryan\AppData\Roaming\Python\Python36\site-packages\poetry\console\application.py", line 112, in get_default_commands
    ConfigCommand(),
  File "C:\Users\Ryan\AppData\Roaming\Python\Python36\site-packages\poetry\console\commands\config.py", line 43, in __init__
    self._config = Config.create("config.toml")
  File "C:\Users\Ryan\AppData\Roaming\Python\Python36\site-packages\poetry\config.py", line 88, in create
    return cls(file)
  File "C:\Users\Ryan\AppData\Roaming\Python\Python36\site-packages\poetry\config.py", line 17, in __init__
    self._content = file.read()
  File "C:\Users\Ryan\AppData\Roaming\Python\Python36\site-packages\tomlkit\toml_file.py", line 20, in read
    return loads(f.read())
  File "C:\Users\Ryan\AppData\Roaming\Python\Python36\site-packages\tomlkit\api.py", line 34, in loads
    return parse(string)
  File "C:\Users\Ryan\AppData\Roaming\Python\Python36\site-packages\tomlkit\api.py", line 51, in parse
    return Parser(string).parse()
  File "C:\Users\Ryan\AppData\Roaming\Python\Python36\site-packages\tomlkit\parser.py", line 143, in parse
    key, value = self._parse_table()
  File "C:\Users\Ryan\AppData\Roaming\Python\Python36\site-packages\tomlkit\parser.py", line 935, in _parse_table
    key_next, table_next = self._parse_table(name)
  File "C:\Users\Ryan\AppData\Roaming\Python\Python36\site-packages\tomlkit\parser.py", line 922, in _parse_table
    item = self._parse_item()
  File "C:\Users\Ryan\AppData\Roaming\Python\Python36\site-packages\tomlkit\parser.py", line 287, in _parse_item
    key, value = self._parse_key_value(True)
  File "C:\Users\Ryan\AppData\Roaming\Python\Python36\site-packages\tomlkit\parser.py", line 394, in _parse_key_value
    val = self._parse_value()
  File "C:\Users\Ryan\AppData\Roaming\Python\Python36\site-packages\tomlkit\parser.py", line 517, in _parse_value
    return self._parse_basic_string()
  File "C:\Users\Ryan\AppData\Roaming\Python\Python36\site-packages\tomlkit\parser.py", line 677, in _parse_basic_string
    return self._parse_string('"')
  File "C:\Users\Ryan\AppData\Roaming\Python\Python36\site-packages\tomlkit\parser.py", line 791, in _parse_string
    InvalidCharInStringError, (self._current,)
tomlkit.exceptions.InvalidCharInStringError: Invalid character 'U' in string at line 4 col 11
```

Where line 4, is this in my `config.toml`: `path = "C:\Users\Ryan\.virtualenvs"`. Col 11 matches up with the first `\`.

As no commands worked, I had to manually update the config file to `C:\\Users\\Ryan\\.virtualenvs`. After this, everything worked as expected again.

**Comment by sdispater** [comment]
Sorry about that!

This might actually be an issue in [TOML Kit](https://github.com/sdispater/tomlkit). I will investigate and get back to you.

**Comment by rcisterna** [comment]
Seems the same error of #386

**Comment by sdispater** [comment]
This is fixed upstream in [TOML Kit](https://github.com/sdispater/tomlkit).

The latest release of Poetry (`0.11.5`) now requires at least TOML Kit 0.4.4 so that the bug does not happen again.
