### ISSUE TITLE
missing dependencies

### ISSUE THREAD

**Issue by toejough** [sdispater/poetry#43]
When installing `bpython` as a dev package, `blessings` is not installed:

```fish
> poetry new shared-mem
Created package shared-mem in shared-mem
> cd shared-mem
> poetry add --dev bpython
Using version ^0.17.1 for bpython

Updating dependencies
Resolving dependencies............


Package operations: 8 installs, 0 updates, 0 removals

Writing lock file

  - Installing cryptography (2.2.2)
  - Installing curtsies (0.3.0)
  - Installing greenlet (0.4.13)
  - Installing ndg-httpsclient (0.4.4)
  - Installing pyasn1 (0.4.2)
  - Installing pygments (2.2.0)
  - Installing pyopenssl (17.5.0)
  - Installing bpython (0.17.1)
> bpython
Traceback (most recent call last):
  File "/<home>/.pyenv/versions/shared-mem/bin/bpython", line 7, in <module>
    from bpython.curtsies import main
  File "/<home>/.pyenv/versions/3.6.4/envs/shared-mem/lib/python3.6/site-packages/bpython/curtsies.py", line 11, in <module>
    import curtsies
  File "/<home>/.pyenv/versions/3.6.4/envs/shared-mem/lib/python3.6/site-packages/curtsies/__init__.py", line 4, in <module>
    from .window import FullscreenWindow, CursorAwareWindow
  File "/<home>/.pyenv/versions/3.6.4/envs/shared-mem/lib/python3.6/site-packages/curtsies/window.py", line 11, in <module>
    import blessings
ModuleNotFoundError: No module named 'blessings'
> 
```

**Comment by sdispater** [comment]
This is the same as #37.

Basically, `curtsies` dependencies do not appear in the JSON API of PyPI which leads to `poetry` not seeing them.

You should probably report this issue upstream (on the `curtsies` repo).

In the meantime, I am working on an hybrid solution to still get dependencies for such packages.

**Comment by sdispater** [comment]
@toejough It should be fixed in the latest version

**Comment by toejough** [comment]
works for me - thanks!  sorry about not catching the duplicate issue, too.
