### ISSUE TITLE
Basic auth credentials are not being URI encoded

### ISSUE THREAD

**Issue by sudiamanj** [sdispater/poetry#686]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: masOS Mojave
- **Poetry version**: 0.12.10

## Issue

I'm installing dependencies from a private PyPICloud server, using this entry in my `pyproject.toml`:

```toml
[[tool.poetry.source]]
name = 'pypicloud'
url = 'http://example.com/simple'
```

First, I've configured my basic auth credentials:

`poetry config http-basic.pypicloud username pass#word`

After that, when attempting to install a dependency, I get this error:

```
[EnvCommandError]
Command ['/Users/sudiamanj/Library/Caches/pypoetry/virtualenvs/foo-py3.7/bin/pip', 'install', '--no-deps', '--trusted-host', 'example.com', '--index-url', 'http://username:pass#word@example.com/simple', 'protobuf==3.6.1'] errored with the following output:
Looking in indexes: http://username:pass#word@example.com/simple
Collecting protobuf==3.6.1
Exception:
Traceback (most recent call last):
  File "/Users/sudiamanj/Library/Caches/pypoetry/virtualenvs/foo-py3.7/lib/python3.7/site-packages/pip/_internal/basecommand.py", line 228, in main
    status = self.run(options, args)
  File "/Users/sudiamanj/Library/Caches/pypoetry/virtualenvs/foo-py3.7/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 291, in run
    resolver.resolve(requirement_set)
  File "/Users/sudiamanj/Library/Caches/pypoetry/virtualenvs/foo-py3.7/lib/python3.7/site-packages/pip/_internal/resolve.py", line 103, in resolve
    self._resolve_one(requirement_set, req)
  File "/Users/sudiamanj/Library/Caches/pypoetry/virtualenvs/foo-py3.7/lib/python3.7/site-packages/pip/_internal/resolve.py", line 257, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/Users/sudiamanj/Library/Caches/pypoetry/virtualenvs/foo-py3.7/lib/python3.7/site-packages/pip/_internal/resolve.py", line 210, in _get_abstract_dist_for
    self.require_hashes
  File "/Users/sudiamanj/Library/Caches/pypoetry/virtualenvs/foo-py3.7/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 245, in prepare_linked_requirement
    req.populate_link(finder, upgrade_allowed, require_hashes)
  File "/Users/sudiamanj/Library/Caches/pypoetry/virtualenvs/foo-py3.7/lib/python3.7/site-packages/pip/_internal/req/req_install.py", line 307, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/Users/sudiamanj/Library/Caches/pypoetry/virtualenvs/foo-py3.7/lib/python3.7/site-packages/pip/_internal/index.py", line 484, in find_requirement
    all_candidates = self.find_all_candidates(req.name)
  File "/Users/sudiamanj/Library/Caches/pypoetry/virtualenvs/foo-py3.7/lib/python3.7/site-packages/pip/_internal/index.py", line 421, in find_all_candidates
    (Link(url) for url in dep_url_loc),
  File "/Users/sudiamanj/Library/Caches/pypoetry/virtualenvs/foo-py3.7/lib/python3.7/site-packages/pip/_internal/index.py", line 423, in <listcomp>
    if self._validate_secure_origin(logger, link)
  File "/Users/sudiamanj/Library/Caches/pypoetry/virtualenvs/foo-py3.7/lib/python3.7/site-packages/pip/_internal/index.py", line 304, in _validate_secure_origin
    origin = (parsed.scheme, parsed.hostname, parsed.port)
  File "/usr/local/anaconda3/lib/python3.7/urllib/parse.py", line 169, in port
    port = int(port, 10)
ValueError: invalid literal for int() with base 10: 'pass'
```

And using pip directly, I get the same error:

```
$ pip install --no-deps --trusted-host example.com --index-url http://username:pass#word@example.com/simple my-dependency
Looking in indexes: http://username:pass#word@example.com/simple
Collecting my-dependency
Exception:
...
  File "/usr/local/anaconda3/envs/rpws/lib/python3.7/urllib/parse.py", line 169, in port
    port = int(port, 10)
ValueError: invalid literal for int() with base 10: 'pass'
```

Per https://github.com/pypa/pip/issues/3267, the solution is to URI-encode the credentials:

```
$ pip install --no-deps --trusted-host example.com --index-url http://username:pass%23word@example.com/simple my-dependency
Looking in indexes: http://example.com/simple
Collecting my-dependency
...
Successfully built my-dependency
```

It would be nice if Poetry could do this for us.

**Comment by sdispater** [comment]
It should be fixed in the latest beta release.
