### ISSUE TITLE
V1.0 doesn't create config files

### ISSUE THREAD

**Issue by jgirardet** [sdispater/poetry#840]
poetry 1.0.02

poetry fresh install `python get-poetry.py --preview`
```
$ poetry config repositories.foo https://bar.com/simple/ -vvv

[FileNotFoundError]
[Errno 2] No such file or directory: '/home/jimmy/.config/pypoetry/config.toml'

Traceback (most recent call last):
  File "/home/jimmy/.poetry/lib/poetry/_vendor/py3.7/clikit/console_application.py", line 131, in run
    status_code = command.handle(parsed_args, io)
  File "/home/jimmy/.poetry/lib/poetry/_vendor/py3.7/clikit/api/command/command.py", line 112, in handle
    status_code = self._do_handle(args, io)
  File "/home/jimmy/.poetry/lib/poetry/_vendor/py3.7/clikit/api/command/command.py", line 160, in _do_handle
    return getattr(handler, handler_method)(args, io, self)
  File "/home/jimmy/.poetry/lib/poetry/_vendor/py3.7/cleo/commands/command.py", line 92, in wrap_handle
    return self.handle()
  File "/home/jimmy/.poetry/lib/poetry/console/commands/config.py", line 173, in handle
    'repositories.{}.url'.format(m.group(1)), url
  File "/home/jimmy/.poetry/lib/poetry/config.py", line 65, in add_property
    self.dump()
  File "/home/jimmy/.poetry/lib/poetry/config.py", line 101, in dump
    fd = os.open(str(self._file), os.O_WRONLY | os.O_CREAT, mode)
```

**Comment by sdispater** [comment]
It has been fixed in #1272
