### ISSUE TITLE
Poetry fails to install SpiderKeeper

### ISSUE THREAD

**Issue by NikolayGalkin** [sdispater/poetry#849]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: OSX 10.14.2 
- **Poetry version**: 1.0.0a2
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/NikolayGalkin/ecd49bed912851b5caf4067a2ef9bc8a

## Issue

Hello! 
Just wanted to add SpiderKeeper to my project. Here is a result:

```bash
Package operations: 1 install, 0 updates, 0 removals

  - Installing spiderkeeper (1.2.0)

[EnvCommandError]
Command ['/Users/galkin/Library/Caches/pypoetry/virtualenvs/test-LqMrd7e9-py3.6/bin/python', '-m', 'pip', 'install', '--no-deps', 'spiderkeeper==1.2.0'] errored with the following output: 
Collecting spiderkeeper==1.2.0
  Could not find a version that satisfies the requirement spiderkeeper==1.2.0 (from versions: 1.0.1.2, 1.0.2.5, 1.0.3.12, 1.1.0, 1.2.2)
No matching distribution found for spiderkeeper==1.2.0


Traceback (most recent call last):
  File "/Users/galkin/.poetry/lib/poetry/_vendor/py3.6/clikit/console_application.py", line 131, in run
    status_code = command.handle(parsed_args, io)
  File "/Users/galkin/.poetry/lib/poetry/_vendor/py3.6/clikit/api/command/command.py", line 112, in handle
    status_code = self._do_handle(args, io)
  File "/Users/galkin/.poetry/lib/poetry/_vendor/py3.6/clikit/api/command/command.py", line 160, in _do_handle
    return getattr(handler, handler_method)(args, io, self)
  File "/Users/galkin/.poetry/lib/poetry/_vendor/py3.6/cleo/commands/command.py", line 92, in wrap_handle
    return self.handle()
  File "/Users/galkin/.poetry/lib/poetry/console/commands/add.py", line 135, in handle
    status = installer.run()
  File "/Users/galkin/.poetry/lib/poetry/installation/installer.py", line 74, in run
    self._do_install(local_repo)
  File "/Users/galkin/.poetry/lib/poetry/installation/installer.py", line 285, in _do_install
    self._execute(op)
  File "/Users/galkin/.poetry/lib/poetry/installation/installer.py", line 293, in _execute
    getattr(self, '_execute_{}'.format(method))(operation)
  File "/Users/galkin/.poetry/lib/poetry/installation/installer.py", line 318, in _execute_install
    self._installer.install(operation.package)
  File "/Users/galkin/.poetry/lib/poetry/installation/pip_installer.py", line 92, in install
    self.run(*args)
  File "/Users/galkin/.poetry/lib/poetry/installation/pip_installer.py", line 113, in run
    return self._env.run('python', '-m', 'pip', *args, **kwargs)
  File "/Users/galkin/.poetry/lib/poetry/utils/env.py", line 818, in run
    return super(VirtualEnv, self).run(bin, *args, **kwargs)
  File "/Users/galkin/.poetry/lib/poetry/utils/env.py", line 677, in run
    raise EnvCommandError(e)
```

P.S. I have installed via pip and it runs correctly. Please help! Have a nice day!

**Comment by bertjwregeer** [comment]
That's fun:

SpiderKeeper 1.2.0 has uploaded a tar.gz for version 1.2.2: https://pypi.org/project/SpiderKeeper/1.2.0/#files

https://files.pythonhosted.org/packages/d9/07/c1d7bd50fbf18e3897daf2e2894aa9ae62e70993570f9a91e420e9acafb2/SpiderKeeper-1.2.2.tar.gz

Pip thinks it is downloading version 1.2.2:

```
Collecting SpiderKeeper
  1 location(s) to search for versions of SpiderKeeper:
  * https://pypi.org/simple/spiderkeeper/
  Getting page https://pypi.org/simple/spiderkeeper/
  Looking up "https://pypi.org/simple/spiderkeeper/" in the cache
  No cache entry available
  Starting new HTTPS connection (1): pypi.org
  https://pypi.org:443 "GET /simple/spiderkeeper/ HTTP/1.1" 200 671
  Updating cache with response from "https://pypi.org/simple/spiderkeeper/"
  Caching due to etag
  Analyzing links from page https://pypi.org/simple/spiderkeeper/
    Found link https://files.pythonhosted.org/packages/ff/25/acf673487e9bd5b02bb8f543af4716d3c7be0f3cb856ca50fed66e7de4b2/SpiderKeeper-1.0.1.2.tar.gz#sha256=c0a02419fa46256b372006453f14417fc1a6769b681620e20f139c93107a634b (from https://pypi.org/simple/spiderkeeper/), version: 1.0.1.2
    Found link https://files.pythonhosted.org/packages/49/05/04e1b47b5b77a3b63f8687044dee7d58d16aab8fb7a8bcd2ae353c1b9967/SpiderKeeper-1.0.2.5.tar.gz#sha256=d94f8e36bd9d410d8a7444fd70c42eb6e49b84dacc7c1e61462cfb4608eeab9e (from https://pypi.org/simple/spiderkeeper/), version: 1.0.2.5
    Found link https://files.pythonhosted.org/packages/f1/39/1dca77f54e685ea38646d3dae06586720d54aa3ad0514c03d046cd63104a/SpiderKeeper-1.0.3.12.tar.gz#sha256=9182fced1854afe59db0d387ee2bce79fa1a21feead4363509b28d172073ded5 (from https://pypi.org/simple/spiderkeeper/), version: 1.0.3.12
    Found link https://files.pythonhosted.org/packages/7a/bc/ef87e149584c9203a9c23e47741ad6911841568c14398f0471a4a65fc784/SpiderKeeper-1.1.0.tar.gz#sha256=69f6ac9a82cbc4dcd3246cfb494d603ff25ddddb9be9d111d5594d628365b27f (from https://pypi.org/simple/spiderkeeper/), version: 1.1.0
    Found link https://files.pythonhosted.org/packages/d9/07/c1d7bd50fbf18e3897daf2e2894aa9ae62e70993570f9a91e420e9acafb2/SpiderKeeper-1.2.2.tar.gz#sha256=25fde8b2f9dbfac1a9b3a0e2ad88cbdf05711dbba276219f9f2c7a1797e06be5 (from https://pypi.org/simple/spiderkeeper/), version: 1.2.2
  Using version 1.2.2 (newest of versions: 1.0.1.2, 1.0.2.5, 1.0.3.12, 1.1.0, 1.2.2)
```
