### ISSUE TITLE
Poetry fails on keyboard add/install requirements

### ISSUE THREAD

**Issue by ST33LDI9ITAL** [sdispater/poetry#978]
- [ x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [ x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Windows 10, Python 3.7.2
- **Poetry version**: 
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: 

## Issue

Python 3.7.2
PIP 19.0.3
Setuptools 40.8.0
Poetry 1.0.0a2
######################################
Using version ^0.13.3 for keyboard

Updating dependencies
Resolving dependencies...

[InvalidRequirement]
Invalid requirement, parse error at "'; <empty'"

**Comment by jacebrowning** [comment]
Please include a link to the contents of your `pyproject.toml` file.

**Comment by ST33LDI9ITAL** [comment]
[tool.poetry]
name = "project"
version = "0.1.0"
description = "test project"
authors = ["ST33L <ST33LDI9ITAL>"]

[tool.poetry.dependencies]
python = "^3.7"
astroid = "^2.2"
autopy = "^1.1"
colorama = "^0.4.1"
guibot = "^0.31.1"
icecream = "^1.4"
isort = "^4.3"
lazy-object-proxy = "^1.3"
mccabe = "^0.6.1"
mouse = "^0.7.0"
mss = "^4.0"
numpy = "^1.16"
opencv-contrib-python = "^4.0"
Pillow = "^5.4"
Pygments = "^2.3"
pylint = "^2.3"
six = "^1.12"
typed-ast = "^1.3"
untokenize = "^0.1.1"
wrapt = "^1.11"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

**Comment by jacebrowning** [comment]
The value of `authors` is invalid: https://poetry.eustace.io/docs/pyproject/#authors

**Comment by ST33LDI9ITAL** [comment]
Yea I know, I edited it to remove my email.
 I think it comes from where it's reporting... line 13 of keyboard's setup.py

  install_requires=["pyobjc; sys_platform=='darwin'"], # OSX-specific dependency

**Comment by ST33LDI9ITAL** [comment]
[InvalidRequirement]
Invalid requirement, parse error at "'; <empty'"

Traceback (most recent call last):
  File "C:\Users\ST33L\.poetry\lib\poetry\_vendor\py3.7\clikit\console_application.py", line 131, in run
    status_code = command.handle(parsed_args, io)
  File "C:\Users\ST33L\.poetry\lib\poetry\_vendor\py3.7\clikit\api\command\command.py", line 112, in handle
    status_code = self._do_handle(args, io)
  File "C:\Users\ST33L\.poetry\lib\poetry\_vendor\py3.7\clikit\api\command\command.py", line 160, in _do_handle
    return getattr(handler, handler_method)(args, io, self)
  File "C:\Users\ST33L\.poetry\lib\poetry\_vendor\py3.7\cleo\commands\command.py", line 92, in wrap_handle
    return self.handle()
  File "C:\Users\ST33L\.poetry\lib\poetry\console\commands\add.py", line 135, in handle
    status = installer.run()
  File "C:\Users\ST33L\.poetry\lib\poetry\installation\installer.py", line 74, in run
    self._do_install(local_repo)
  File "C:\Users\ST33L\.poetry\lib\poetry\installation\installer.py", line 214, in _do_install
    ops = solver.solve(use_latest=whitelist)
  File "C:\Users\ST33L\.poetry\lib\poetry\puzzle\solver.py", line 38, in solve
    packages, depths = self._solve(use_latest=use_latest)
  File "C:\Users\ST33L\.poetry\lib\poetry\puzzle\solver.py", line 171, in _solve
    self._package, self._provider, locked=locked, use_latest=use_latest
  File "C:\Users\ST33L\.poetry\lib\poetry\mixology\__init__.py", line 7, in resolve_version
    return solver.solve()
  File "C:\Users\ST33L\.poetry\lib\poetry\mixology\version_solver.py", line 79, in solve
    next = self._choose_package_version()
  File "C:\Users\ST33L\.poetry\lib\poetry\mixology\version_solver.py", line 380, in _choose_package_version
    for incompatibility in self._provider.incompatibilities_for(version):
  File "C:\Users\ST33L\.poetry\lib\poetry\puzzle\provider.py", line 435, in incompatibilities_for
    for dep in dependencies
  File "C:\Users\ST33L\.poetry\lib\poetry\puzzle\provider.py", line 435, in <listcomp>
    for dep in dependencies
  File "C:\Users\ST33L\.poetry\lib\poetry\packages\package.py", line 346, in to_dependency
    return dependency_from_pep_508(name)
  File "C:\Users\ST33L\.poetry\lib\poetry\packages\__init__.py", line 34, in dependency_from_pep_508
    req = Requirement(name)
  File "C:\Users\ST33L\.poetry\lib\poetry\version\requirements.py", line 202, in __init__
    requirement_string[e.loc : e.loc + 8]
